### ISSUE TITLE
Drawing to edge produces wierd lines on Chrome

### ISSUE THREAD

**Issue by rkrishnamoorthy** [literallycanvas/literallycanvas#247]
On Chrome, when you draw a line to the edge using the drawing tool, it produces a wierd line on top, bottom and left edges of the canvas. 

this issue does not occur on firefox though.

![image](https://cloud.githubusercontent.com/assets/9877288/5137515/e131502a-7175-11e4-9365-c67c311994af.png)

thanks
Rajesh

**Comment by irskep** [comment]
I don't think this particular thing happens anymore, but now #272 is a thing. Not as bad but still crappy.

**Comment by rkrishnamoorthy** [comment]
thanks for looking into this. Will test it out

Best
Rajesh
