### ISSUE TITLE
Allow changing default stroke width (5px is too wide for some users)

### ISSUE THREAD

**Issue by saintthor** [literallycanvas/literallycanvas#252]
5px is too wide.

**Comment by atteism** [comment]
Looking forward to this feature!

**Comment by irskep** [comment]
I'll put configurable stroke width options in the next release.

Any requests for new defaults?

**Comment by atteism** [comment]
Great news, thank you! Maybe keep the default default so previous users get what they are used too?

**Comment by irskep** [comment]
Implemented in master. I'll release 0.4.5 shortly.
