### ISSUE TITLE
Overriding a shape in defineShape seems to result in strange behavior

### ISSUE THREAD

**Issue by saintthor** [literallycanvas/literallycanvas#253]
to overload some methods of Line, i copied the defineShape( 'Line', ... )  from literrallycanvas.js. 
( is it the best way to overload methods of exist shapes? )

i didn't alter the code in defineShape except changing 
createShape
to 
LC.createShape.

run, i draw the solid or dash lines well. but once i select the arrow line and click to draw it, the canvas goes right quickly and soon out of the window. i can not pan it back.

**Comment by irskep** [comment]
Sorry for missing this. Could you include the source code that demonstrates the problem?

**Comment by irskep** [comment]
I'm guessing you didn't have `lineEndCapShapes` in scope, which is an internal object. So this isn't a bug, just an unsupported feature.
