### ISSUE TITLE
for rectangle and ellips, json export 'color' but must be set as 'strokeColor' when import

### ISSUE THREAD

**Issue by saintthor** [literallycanvas/literallycanvas#254]
for rectangle and ellips, json export 'color' but must be set as 'strokeColor' when import.

**Comment by irskep** [comment]
Thanks for this bug report and the other one. Will fix soon (unless some kindly soul gets to it first).

**Comment by irskep** [comment]
Rectangle and Ellipse both export `strokeColor` and `fillColor` as expected. Perhaps you're using an outdated version?

**Comment by irskep** [comment]
Closing unless more information is provided.
