### ISSUE TITLE
fatal: ellipse causes no response

### ISSUE THREAD

**Issue by saintthor** [literallycanvas/literallycanvas#255]
after drawing many lines or rects, to draw some ellipse, nothing could be add to canvas. neither ellipse nor rect nor line.

**Comment by irskep** [comment]
I can't reproduce this issue. Here are some lines, rects, and ellipses I drew without issue.

![](http://dl.dropbox.com/u/360865/Screenshots/o4.png)

**Comment by irskep** [comment]
Closing until more information is provided.

**Comment by saintthor** [comment]
it happens in firefox 36.0.1. draw line and rectangles first, then draw some ellipses, it should take place.
in chrome it is fine.

**Comment by irskep** [comment]
Can't repro in Firefox 37.

**Comment by saintthor** [comment]
unfortunately, in firefox 38,
draw 5 rects, ok;
draw 1 ellips, ok;
draw the 2nd ellips, fail;
then nothing could be drawn.
