### ISSUE TITLE
LiterallyCanvas.setTool isn't documented

### ISSUE THREAD

**Issue by razuro** [literallycanvas/literallycanvas#256]
Noob alert. For example I've tried changing to Eraser:

lc.toolChange(Eraser);
lc.toolChange({Eraser});
lc.toolChange(lc.tools.Eraser);

But it's not working. Can someone point me to the correct direction?
Thanks.

**Comment by irskep** [comment]
At first I thought "this has got to be in the docs. I'll go find a link." Then I looked for it in the docs and couldn't find it. So, good catch. Updating this issue to say it's a docs bug.

Here's what should go in the docs, in `LiterallyCanvas.rst`:

```rst
Setting the tool
^^^^^^^^^^^^^^^

.. js:function:: setTool(toolInstance)

  Sets the current tool to `toolInstance`, which should be an instance of an `LC.tools.Tool` subclass.

  For example:

  .. code-block:: javascript
    lc.setTool(new LC.tools.Eraser())
```

If you have any additional questions, please subscribe to the mailing list. Thanks!

**Comment by irskep** [comment]
Bonus points if you submit a pull request to the docs repo. :-)

**Comment by razuro** [comment]
That was so quick! Actually I was struggling for hours yesterday finding how to do this in the docs. Should have done earlier. Thank you.
