### ISSUE TITLE
How to add transparent marker (Stabilo) tool

### ISSUE THREAD

**Issue by dstainhauser** [literallycanvas/literallycanvas#260]
I'd like to use literally canvas to annotate images with text markers. Therefore, a tool that allows to choose one of three semi-transparent marker colors would be ideal. It could then work like LinePath, but having a hsla with alpha 0.5 instead of hsl.
I tried quickly by changing the two lines using hsl to hsla with an alpha value and it would work perfectly.

My question: I'm not aware of CoffeeScript. How can I add a tool by plain JavaScript? 
My wish: Wouldn't this be a nice tool to add to the predefined tools?

Thanks for help.

**Comment by irskep** [comment]
> My question: I'm not aware of CoffeeScript. How can I add a tool by plain JavaScript?

[Here's the documentation for how to define a tool.](http://literallycanvas.com/api/tools.html) The code samples are in Coffeescript, but you should be able to adapt them. You can add your own tools without having them built in.

I'd have to see the full implementation to determine whether it should be added to the predefined tools.

**Comment by dstainhauser** [comment]
Hi Steve
> Literally Canvas is developed in CoffeeScript, and all of our internal examples use CoffeeScript, so this example will be in CoffeeScript. We will add documentation in JavaScript if there is sufficient demand. (As usual, please express demand via GitHub issues.)

Thats actually what I asked for some help. Once I know how to integrate a tool written in JS, I would add it. Is there already some documentation how to add a Tool written in JavaScript?

**Comment by irskep** [comment]
Ah, I'd forgotten about that.

There is still no documentation to write a tool in JS, but the transformation from Coffeescript is pretty simple. Here's the line tool used in the example, written in JS (I didn't try to run it):

```javascript
# reimplementation of the built-in line tool
var MyLine = function() {
  this.strokeWidth = 5
}

MyLine.prototype.name = 'MyLine'
MyLine.prototype.iconName = 'line'
MyLine.prototype.optionsStyle = 'stroke-width'
MyLine.prototype.begin = function(x, y, lc) {
  // make the shape we will be working with, in this case a line
  this.currentShape = LC.createShape('Line', {
    x1: x, y1: y, x2: x, y2: y, this.strokeWidth,
    color: lc.getColor('primary')})
}

MyLine.prototype.continue = function(x, y, lc) {
  // lifecycle: mouse is dragging
  // update the shape based on latest state (just set the other end)
  this.currentShape.x2 = x
  this.currentShape.y2 = y
  # render the shape to the canvas without adding it to the drawing
  lc.update(this.currentShape)
}

MyLine.prototype.end = function(x, y, lc) {
  // lifecycle: mouse was released
  // save the shape as part of the drawing
  lc.saveShape(this.currentShape)
}
```

Or a more concise, less prototypey version:'

```javascript
# reimplementation of the built-in line tool
var MyLine = function() {
  var self = this;
  self.strokeWidth = 5
  self.name = 'MyLine'
  self.iconName = 'line'
  self.optionsStyle = 'stroke-width'
  self.begin = function(x, y, lc) {
    // make the shape we will be working with, in this case a line
    self.currentShape = LC.createShape('Line', {
      x1: x, y1: y, x2: x, y2: y, self.strokeWidth,
      color: lc.getColor('primary')})
  }

  self.continue = function(x, y, lc) {
    // lifecycle: mouse is dragging
    // update the shape based on latest state (just set the other end)
    self.currentShape.x2 = x
    self.currentShape.y2 = y
    # render the shape to the canvas without adding it to the drawing
    lc.update(self.currentShape)
  }

  self.end = function(x, y, lc) {
    // lifecycle: mouse was released
    // save the shape as part of the drawing
    lc.saveShape(self.currentShape)
  }
}
```

I haven't written out JS classes in a while, so my idioms might be a little rusty. I hope that helps.

**Comment by irskep** [comment]
Was this enough to get you going? Is there anything else you need help with? I want people to be able to get things done. :-)

**Comment by dstainhauser** [comment]
Hi Steve

Thanks for asking. I really would like to add this feature. But currently there is no time that I can plan for this. We want to add this feature by this summer and will then extend the transparency. We will let you know.  


Best regards


Daniel 

Daniel Stainhauser
Geschäftsführer
Master of Science (MSc)

ionesoft GmbH
Sandrainstrasse 17
CH-3007 Bern
tel: +41 32 513 3991

ionesoft GmbH
Postfach 19
CH-3303 Jegenstorf
tel: +41 31 761 3770

dstainhauser@ionesoft.ch
http://ionesoft.ch
