### ISSUE TITLE
JSON to SVG

### ISSUE THREAD

**Issue by dstainhauser** [literallycanvas/literallycanvas#261]
Has anyone worked on the conversion of the JSON provided by lc.getSnapshotJSON() to SVG. I'd like to preview the result of editing an image by literally canvas in a html 5 page by using standard SVG, without having to include the editor. It looks straight forward to do the transformation, but still a bit work that might be reused.

**Comment by irskep** [comment]
Interesting idea. AFAIK, no one's attempted this.

**Comment by irskep** [comment]
This might help you in lieu of SVG. It just renders LC shapes to the canvas. You'd have to use a couple of internal API functions (and figure out what they are, hehe) but it's definitely doable.

http://literallycanvas.com/api/util.html#LC.util.renderShapes

**Comment by irskep** [comment]
This and #175 will require decoupling of image exports from the `LiterallyCanvas` object.

**Comment by irskep** [comment]
This is done for v0.4.5.

**Comment by dstainhauser** [comment]
Hi Steve

Great. When will 0.4.5 be available for download? Shall I test a prerelease?

Is the font problem also solved, #259?

Best regards

Daniel

________________________
Daniel Stainhauser
Geschäftsfüher
Master of Science (MSc)

ionesoft GmbH
Sandrainstrasse 17
CH-3007 Bern
tel: +41 32 513 3991

ionesoft GmbH
Postfach 19
CH-3303 Jegenstorf
tel: +41 31 761 3770

dstainhauser@ionesoft.ch
http://ionesoft.ch

**Comment by irskep** [comment]
#256 is not a bug in Literally Canvas; see my response over on that thread.

I don't know when 0.4.5 will be ready. You can check out the repo, run `gulp`, and pull out `lib/js/literallycanvas.js` any time you want.

**Comment by irskep** [comment]
You should subscribe to the mailing list for release updates; 0.4.4 came out 2 weeks ago.

**Comment by irskep** [comment]
This works on the current master branch:

```js
var snapshotJSON = localStorage['saved-snapshot'];
var svgString = LC.renderShapesToSVG(
  LC.snapshotJSONToShapes(snapshotJSON),
  {x: 0, y: 0, width: 100, height: 100}, // have to manually define bounds
  'transparent');
```

**Comment by dstainhauser** [comment]
Hi Steve

Nice changes you did with the new version.

I tried to upgrade to the new version 4.5.0, but there were some issues:

1. No arrow and no dash line pattern anymore. I had them when I was using the old react.js. With the suggested new one, they are gone.
2. When using the line tool, changing the line thickness did not work. Tested with Firefox and Safari using the website on a Mac and iPad
3. The new polygon fill tool did not work in my app. It shifted the position. Tapping at x1y1 showed the line at x2y2, about 100px shifted. But running with your demo is ok. I assume it is a problem because I’m zooming the drawing. Have to investigate this more.
4. Text tool:How can I adjust the text size and font?

If I should report this on github let me know.

Best regards

Daniel

**Comment by irskep** [comment]
Thank you so much for testing! Obviously my QA leaves much to be desired.

I just opened tickets #303, #304, and #305 for your findings 1-3. For #4, use the toolbar as usual. You probably didn't see it because one of the earlier bugs you found caused an exception that broke the toolbar.

**Comment by irskep** [comment]
(I'll try to fix this stuff today)

**Comment by irskep** [comment]
Fixed 1, 2, and 4 in the development build.

**Comment by irskep** [comment]
Fixed 3. Please try it out. This ought to work: https://gist.githubusercontent.com/irskep/39e8516165b8381190a0/raw/adbbfb1b09932737b4656233e8e466cc3e3df299/literallycanvas.js

**Comment by dstainhauser** [comment]
Hi Steve

That was quick, many thanks. I’ve tested it on iPad. Using react 0.13.3 did not work at all, always got an error that LC.init could not be initialized. Don’t see why. Then I took the old 0.12.2 version and it looks like this is fine too. 

I again hat to remove the fonts with spaces. I’v seen that you have stated it will be an encoding problem, but I didn’t see where. As I don’t need all those fonts, I just removed them. Have to investigate it once on my side.

1. fixed
2. fixed
3. fixed
4. toolbar is back, but it does not really work nicely. The previous version was perfect on ipad. When I tab the text frame, I can’t start typing. I have to long press until the keyboard appears. Also the text is shifted aside and stays there. After clicking on any other place, it goes into the text frame. Could this be due to the wrong react library?

Using 0.4.4 from your website is working fine on the ipad. Haven’t tested with 0.4.5 so far.


May I ask for a feature that would be very useful?

Would it be possible to set a transparency value  for lines and background, beside the color? This would allow to make annotations in the way of a text marker, i.e. highlight text on a drawing. I’ve added this once in an earlier version. It is actually just using rgba instead of rgb and specifying an alpha value. I did it hard coded in the js, as I’m not familiar with the development language.

Finally I could then add some more toolbar items with the four textmarkers yellow, green, blue and red to easily pick them and highlight stuff.

This is just an idea, if you feel it could be useful for others too. 

Let me know if I should test more. Any idea why react 0.13.3 is not working? Has it to be initialised differently?

Regards

Daniel

**Comment by dstainhauser** [comment]
Found the problem with react 13.3. I’ve downloaded the version without addons. Working now with 0.13.3, but the same problem with typing text on the ipad.

**Comment by irskep** [comment]
I'm moving this discussion to the mailing list. GitHub issues are for reporting and discussing individual features and bugs.

**Comment by irskep** [comment]
Regarding your feature request, there's an open ticket for an opacity slider on the color picker. Text backgrounds are probably too complicated for now though.

**Comment by irskep** [comment]
Posted another fix-up build to the mailing list.
