### ISSUE TITLE
Question/Feature Request: Set pan to background image size

### ISSUE THREAD

**Issue by dstainhauser** [literallycanvas/literallycanvas#263]
Is there a way that the editor zooms exactly to the size of the background image? Is there a parameter to set the zoom/pan?

Thx for feedback.

**Comment by irskep** [comment]
There is no built-in method to do what you want, but `lc.setPan()` and `lc.setZoom()` will let you implement it yourself.

**Comment by dstainhauser** [comment]
Awesome, this works. Thanks Steve
