### ISSUE TITLE
Export bounding rect of all shapes doesn't export entire Background Image

### ISSUE THREAD

**Issue by r31griffo** [literallycanvas/literallycanvas#265]
Hi guys,

Firstly a big thankyou to all involved in this project, I'm putting together a basic webapp for my installers so they can make quick draft changes to floorplans.  The interface provided by your API is perfect for them; simple and easy to use.

I'm not sure if this is an issue or not, admittedly I'm not great at Javascript (I'm terrible) so I may have done something wrong here.  Using the examples on the website I have a working drawing interface with a background image and I can export to PNG...later I will POST and save to the webserver via PHP.

The problem I'm having is when I export to PNG the exported image only contains the images I've drawn on top of the background and parts of the background that are between these shapes.

Is there a better way for me to deal with these issues or potentially I've done something wrong?

The only idea that has come to mind is putting the image in the background AND foreground, this way Export PNG would export the entire size of the image...but the clear button would remove the foreground image

Thanks in advance for your suggestions.

Cheers,
Brad

**Comment by irskep** [comment]
You can explicitly pass the bounding rect of your background image to `lc.getImage()`.

```js
lc.getImage({rect: {x: 0, y: 0, width: imageWidth, height: imageHeight}})
```

Does that solve your problem?

**Comment by r31griffo** [comment]
Thanks for the quick reply, that's exactly what I needed to make it happen.

    $('.controls.export [data-action=export-as-png]').click(function(e) {
      e.preventDefault();
      window.open(lc.getImage({rect: {x: 0, y: 0, width: backgroundImage.width, height: backgroundImage.height}}).toDataURL());
    });
