### ISSUE TITLE
dosn't lc support any version of ie?

### ISSUE THREAD

**Issue by saintthor** [literallycanvas/literallycanvas#267]
i tested. even in ie11 fails.

**Comment by irskep** [comment]
With what error?

**Comment by saintthor** [comment]
let me catch it tomorrow.

from which version do you think should be ok?

**Comment by irskep** [comment]
See footnote here. 10+, with a polyfill. That might be the issue you're
seeing. http://literallycanvas.com/#f2


On Mon, Feb 23, 2015, at 09:18 AM, saintthor wrote:
> let me catch it tomorrow.


> from which version do you think should be ok?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/literallycanvas/literallycanvas/issues/267#issuecomment-75587371

**Comment by saintthor** [comment]
is there any demo on using polyfill?

**Comment by irskep** [comment]
No, just add the JS to your page.


On Mon, Feb 23, 2015, at 10:21 PM, saintthor wrote:
> is there any demo on using polyfill?


> — Reply to this email directly or view it on GitHub[1].

>


Links:

  1. https://github.com/literallycanvas/literallycanvas/issues/267#issuecomment-75705922

**Comment by saintthor** [comment]
i am sorry. which js do you mean? where is it?

**Comment by irskep** [comment]
Ack, Mozilla removed it from their page since I added the link to the LC site! Here's the JS:

I haven't tested this, but it ought to work: https://raw.githubusercontent.com/d4tocchini/customevent-polyfill/master/CustomEvent.js

**Comment by saintthor** [comment]
thank you. it works.
