### ISSUE TITLE
Opacity slider for stroke and fill colors

### ISSUE THREAD

**Issue by dstainhauser** [literallycanvas/literallycanvas#268]
I would appreciate if there where a opacity tool for stroke and fill color. One level would be sufficient for using on both colors. Are there any plans to create such a tool?

**Comment by irskep** [comment]
There are generally no plans at all in this project, since no one dedicates resources to improving it. I'm currently busy with other things.

This is a reasonable request, and it would be lovely if someone took care of it.

**Comment by mccambridge** [comment]
I couldn't find an issue related to this. Before I create one, I'll just ask: is there a way to set the initial opacity for the slider? Looks like it defaults to 0, and I think this could be confusing for users.

**Comment by irskep** [comment]
That sounds like a straight up bug.

**Comment by mccambridge** [comment]
:anguished: ah, that would make sense. thanks!
