### ISSUE TITLE
draw point different in firefox and chrome/ie

### ISSUE THREAD

**Issue by saintthor** [literallycanvas/literallycanvas#269]
using line tool, set width to 3px, click on canvas, in firefox i draw a circle with r=3px.

export the json and import in chrome or ie, there is no such circle. to import in firefox is well.

**Comment by irskep** [comment]
Is this the same as #255 or #254? Can you provide the string you're importing, with just the one circle in it?

**Comment by saintthor** [comment]
not same. 
it is nothing about importing. just drawing is defferent.
acctually i am drawing a point by one click with the Line tool with width = 3px. in firefox i can draw a big point like a circle in this way, while draw nothing in chrome or ie.
it seems to draw a line (( x0, y0, ), ( x1, y1 )), if x0 == x1 and y0 == y1, in firefox it draws a point and in chrome not.

you may test by these steps:
1, select line tool and set width to a big value.
2, single click on cavas, do not drag.
if you are using firefox you get a bit point like a circle. but in chrome you get nothing.

**Comment by saintthor** [comment]
by the way, to draw a rectangle or ellipse with x0 == x1 or y0 == y1, in chrome get nothing while in firefox get a line.

**Comment by irskep** [comment]
Fixed for v0.4.5.
