### ISSUE TITLE
iPad4 shrinking on export

### ISSUE THREAD

**Issue by r31griffo** [literallycanvas/literallycanvas#270]
Hi,

When exporting the image I have a funny issue with my iPad4 that I'm able to replicate time and again.  The image loads correctly and I have no issues editing it, but when exporting the image on this device the image is shrunk (not cropped) to nearly half of its original size.

This was happening with iOS 7.1.2 so I updated to 8.1.3 but there's no change.  Interestingly I have an iPad Air with iOS 8.1.3 and it works fine on that.

I've also tested this on Google Chrome or Firefox but these don't suffer the issue.

I didn't see another issue similar to this, I hope it's an easy fix.

Cheers,
Brad

Sample of code used below:

<script>
  $(document).ready(function() {
    var backgroundImage = new Image()
        backgroundImage.src = 'floorplan.png';

    var lc = LC.init(
        document.getElementsByClassName('literally backgrounds')[0],
        {
          backgroundShapes: [
            LC.createShape(
              'Image', {x: 0, y: 0, image: backgroundImage, scale: 1}),
          ]
        });

function setValue(){
    document.sampleForm.floorplan.value = lc.getImage({rect: {x: 0, y: 0, width: backgroundImage.width, height: backgroundImage.height}}).toDataURL();
    document.forms["sampleForm"].submit();
}

    $('.controls.export [data-action=export-as-png]').click(function(e) {
      e.preventDefault();
      var data = lc.getImage({rect: {x: 0, y: 0, width: backgroundImage.width, height: backgroundImage.height}}).toDataURL();
      var element = document.getElementById("floorplan");
      element.value = data;
      element.form.submit();
    });

  });

</script>

**Comment by campaul** [comment]
I suspect this has something to do with device pixel ratio, but I'm not really sure.

**Comment by r31griffo** [comment]
I'll apologise in advance, I'm really very new to javascript and front end code...

With your comments in mind I tried changing the 'scale' of the backgroundImage from 1 to 0.5 and also to 2 but this doesn't appear to have an affect...

As a test, I also removed from the head:
<meta name="viewport" content="width=device-width, initial-scale=1">

Is there a way to turn off scaling on an iPad either through code or via a setting on the device? This would at least identify the culprit.  I'm happy to do the leg work to diagnose the issue but I'd need you to tell me what you need...


Code pasted below again, it didn't show last time
  $(document).ready(function() {
    var backgroundImage = new Image()
        backgroundImage.src = 'floorplan.png';

    var lc = LC.init(
        document.getElementsByClassName('literally backgrounds')[0],
        {
          backgroundShapes: [
            LC.createShape(
              'Image', {x: 0, y: 0, image: backgroundImage, scale: 1}),
          ]
        });


function setValue(){
    document.sampleForm.floorplan.value = lc.getImage({rect: {x: 0, y: 0, width: backgroundImage.width, height: backgroundImage.height}}).toDataURL();
    document.forms["sampleForm"].submit();
}

    $('.controls.export [data-action=export-as-png]').click(function(e) {
      e.preventDefault();
      var data = lc.getImage({rect: {x: 0, y: 0, width: backgroundImage.width, height: backgroundImage.height}}).toDataURL();
      var element = document.getElementById("floorplan");
      element.value = data;
      element.form.submit();
    });

  });

**Comment by irskep** [comment]
I'm guessing you want to use `lc.getImage({scaleDownRetina: false})`, to get full pixel resolution.

**Comment by irskep** [comment]
I'm closing this, but you can reopen if that isn't the solution.
