### ISSUE TITLE
Cannot save when add big image as background

### ISSUE THREAD

**Issue by nobutsta** [literallycanvas/literallycanvas#271]
Hello,
I tried set up big image from my camera as a background so we can draw a cartoon on it. But finally I can save it into file for some reason. It seems like those encoded image cannot send through. This is my code before sending.

      $(document).ready(function() {
        // disable scrolling on touch devices so we can actually draw
        $(document).bind('touchmove', function(e) {
          if (e.target === document.documentElement) {
            return e.preventDefault();
          }
        });

        LC.setDefaultImageURLPrefix('icons/');		

        var backgroundImage = new Image();
        backgroundImage.src = '<?=urldecode($_GET[file]);?>';

		var logo = new Image();
        logo.src = 'images/logo153x60.png'

        // the only LC-specific thing we have to do
        var containerOne = document.getElementsByClassName('workSpace')[0];
        var lc = LC.init(containerOne, {
			imageSize: {width: 1200, height: 800},
          backgroundShapes: [
            LC.createShape('Image', {image: backgroundImage, x: 0, y: 0, image: backgroundImage, scale: 1}),//position of background
			LC.createShape('Image', {image: backgroundImage, x: 10, y: 690, image: logo, scale: 1})//logo
          ]
        });
        window.demoLC = lc;
        lc.loadSnapshotJSON(localStorage.getItem('drawing'));//load previous drawing

        lc.on('drawingChange', function() {
          localStorage.setItem('drawing', lc.getSnapshotJSON());
        });

         //lc.setPan(100, 100);
		 lc.setImageSize(1200, 800);//set the reset image size
		//var exportIMG=lc.getImage({rect: {x: 0, y: 0, width: 800, height: 600},scale: 1}).toDataURL();
        
		$('[data-action=exportIMG]').click(function(e) {
		  e.preventDefault();

		  $('.export_btn').html('Saving...')
		  // this is all standard Imgur API; only LC-specific thing is the image
		  // data argument;
		  $.ajax({
			url: 'print.php',
			type: 'POST',
			data: {
			  // convert the image data to base64
				filename:'<?=$_GET[file]?>',
				image:  lc.canvasForExport().toDataURL().split(',')[1]
			},
			success: function(data) {
				if(jQuery.trim(data) === "ok"){
					$('#saveModal').modal('show'); 
					$(".modal-title").html("Luckily");
					$(".modal-body").html("<span class=\"text-success\">Photo saved</span>");
					//$(".modal-body").html(data);
				  }else{
					$('#saveModal').modal('show'); 
					$(".modal-title").html("Error");
					//$(".modal-body").html("<span class=\"text-danger\">Cannot save</span>");
					$(".modal-body").html(data);
					
				  }//if
				  //setTimeout(function() { $('#saveModal').modal('hide'); }, 2000);//hide modal after 2 sec
			},//success
		  });
		  return false;
		});//click(function(e)
      });

I am searching for couple of days for this but no luck. Please point me out.

**Comment by campaul** [comment]
Just to confirm, does your code work if you try with a smaller image?

**Comment by nobutsta** [comment]
Yes, it works when I use a smaller image (800x600) or less detail.

This one work : http://s2.postimg.org/bzjv7uojt/dino_1426086293.png
This is not : http://www.ifreewallpaper.com/wallpapers_download/mobile/1200_800_wallpapers/20110904/B/B_flowers_boykxy2j.jpg

I tried to diagnose it from console or error but there's none.

**Comment by irskep** [comment]
There are a few things that could be going on here.

I notice you're trying to use the Imgur API. Maybe they're limiting the size of the image? Try installing this plugin in Chrome: https://github.com/jffry/console.image-chrome-extension

Then, in your button click handler, try this instead of the Imgur RPC call:

```js
console.image(lc.canvasForExport().toDataURL())
```

That should show your exported image in the console. That way you can see if it's Literally Canvas or Imgur that's the problem.

**Comment by irskep** [comment]
Since I never got any followup for this, I'm assuming it wasn't our fault or doesn't matter. Feel free to comment if that's not the case.

**Comment by nobutsta** [comment]
Hello, since that day. My problem hasn't solved yet. The problem is still with the `setZoom()`. The photo I use for the background(3696x2448) was taken from a camera. Which is bigger than the viewing area of the program (1016x665px). So I set the zoom to `setZoom(0.28)`. This perfectly fit the view area. But the other problem is. When an export button is clicked. The picture with drawing is not come out as it suppose to be. 

I also tried resized the original photo to 1016x665. And use it as a background image. With no `setZoom()` function. This not export the picture too! I think the problem is around the setting the view zoom.

Please suggest,

**Comment by nobutsta** [comment]
This is `print.php` script.

<?php
header('Content-Type: image/jpeg');
ini_set('memory_limit', '32M');
$data=$_POST['image'];
if(!$_POST['filename']){
	exit("error");
}
list($dir,$folder,$file)=explode("/",$_POST['filename']);
$ext=strtolower(pathinfo($_POST['filename'], PATHINFO_EXTENSION));

$file=basename($file,".".$ext);
//$data = substr($data, strpos($data, ",")+1);
$data = base64_decode($data);

$imgRes = imagecreatefromstring($data);
if($imgRes !== false && imagejpeg($imgRes, $file,"100") === true)
	if(!is_dir($dir.'/'.$folder.'/new/')){
		mkdir($dir.'/'.$folder.'/new/',0777);
	}
	$photo=$dir.'/'.$folder.'/new/'.$file.'-'.time().".".$ext;//print directly
	if(file_put_contents($photo, $data)){		
		//echo "<script type=\"text/javascript\">window.open(\"print_out.php?file=$photo\", \"Printing...\", \"width=1, height=1\");</script>";//open new window and print
		//echo "ok";
	}else{
		echo "error";
	}
imagedestroy($imgRes);
?>

**Comment by irskep** [comment]
Thanks for the clue. I'll look into it.

**Comment by nobutsta** [comment]
irskep, I found the problem. It is about the server. I was installed apache 2.2 and it nearly pulled my hair out over the night. When I updated to apache 2.4, everything works perfectly. Thanks for your reply and your superb software.

Please keep in touch with the program, don't quit it. Let me know if you launch any commercial version.

Regards,
