### ISSUE TITLE
I wannn create a tool to my app,what is i can do?

### ISSUE THREAD

**Issue by 178620086** [literallycanvas/literallycanvas#275]
then i want to create a app to paint some image .
so ,i wann add icon to the bar but i don't know how to do?
can you help me ? 

thank you

**Comment by irskep** [comment]
Relevant documentation http://literallycanvas.com/api/tools.html


On Thu, Apr 16, 2015, at 01:18 AM, 178620086 wrote:
> then i want to create a app to paint some image .
>
so ,i wann add icon to the bar but i don't know how to do?
>
can you help me ?

> thank you


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/literallycanvas/literallycanvas/issues/275

**Comment by 178620086** [comment]
thank you so.
but I have other qustion 
if the object "shape"  added the "drawing" then an wann edit the "shape" use mouse,for example  add big or small.
I want ask the shape have event callbak? how to control they?

**Comment by irskep** [comment]
You can mutate a shape's attributes to change how it renders. The
easiest way to learn about that is to read the source code.


On Thu, Apr 16, 2015, at 08:29 PM, 178620086 wrote:
> thank you so.
>
but I have other qustion
>
if the object "shape" added the "drawing" then an wann edit the "shape"
use mouse,for example add big or small.
>
I want ask the shape have event callbak? how to control they?

> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/literallycanvas/literallycanvas/issues/275#issuecomment-93885701
