### ISSUE TITLE
Setting background color on init doesn't work

### ISSUE THREAD

**Issue by magic-lantern** [literallycanvas/literallycanvas#277]
I noticed that in Safari/Chrome/Firefox, if you initialize a literallycanvas object with any background color, it doesn't do anything. Manually changing the background color via the UI works...

For example, this initialization:

      var lc = $('.literally').literallycanvas({
        imageURLPrefix: 'external/bower_components/literallycanvas/img/',
        backgroundColor: 'white'
      });

results in a transparent background just as this does:

      var lc = $('.literally').literallycanvas({
        imageURLPrefix: 'external/bower_components/literallycanvas/img/'
      });

The only difference is that the background color selector shows initialized color

**Comment by irskep** [comment]
Good catch, thanks for the report.

**Comment by magic-lantern** [comment]
I noticed a way to get around the background color bug. After creating the object, I load an empty canvas with the desired colors and it then sets it to what I want.

lc.loadSnapshotJSON('{"shapes":[],"colors":{"primary":"#000","secondary":"#fff","background":"white"}}');

**Comment by irskep** [comment]
You are awesome, and I will reward you by fixing this as soon as I can manage, and finally releasing 0.4.2.
