### ISSUE TITLE
Toolbars at the top

### ISSUE THREAD

**Issue by shawky** [literallycanvas/literallycanvas#280]
I would lik to know how to put both toolbars at the tob of the canvas.

**Comment by irskep** [comment]
Basically you can't.

**Comment by 178620086** [comment]
.literally .lc-options {
      top: 0px;
  right: 0;
  bottom: 0;
  left: 31px;
  cursor: default;
}

**Comment by irskep** [comment]
I am happy to report that v0.4.5 (unreleased, currently the master branch) has a `toolbarPosition` option whose default is `'top'` but which also supports `'bottom'`.
