### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Tharickahamed** [literallycanvas/literallycanvas#290]
Hey,

Thanks for the cool tool, I can see "Export as PNG", by the way how could I find "Download as PNG"?

**Comment by irskep** [comment]
Github issues are for bugs and feature requests, not support. Please use the mailing list, and try reading the docs first.

**Comment by irskep** [comment]
Specifically, read about data URIs. This project's responsibilities do not overlap with what you are asking.
