### ISSUE TITLE
how to insert a image to Drawing board

### ISSUE THREAD

**Issue by 178620086** [literallycanvas/literallycanvas#291]
i try to create a tools to insert a image but can not edit agin.
not to rotation or  enlarge ,narrow 。

it import thing is a shap can not to edit  when it inserted.

 how to do ?

thank yon

**Comment by irskep** [comment]
The basic tool API is much more MS Paint than Adobe Illustrator.

Look at the new polygon tool for an example of something more sophisticated.

Please use the mailing list for future questions of this nature (i.e. not bug reports or feature requests).
