### ISSUE TITLE
JavaScript tool API and docs

### ISSUE THREAD

**Issue by irskep** [literallycanvas/literallycanvas#298]
It's lame that the docs and APIs for writing tools are all in CoffeeScript.

**Comment by irskep** [comment]
I decided this isn't necessary.

**Comment by 178620086** [comment]
why not necessary?

**Comment by irskep** [comment]
Because it's already JS friendly, I just explained it badly. :-)

I released v0.4.5 literally two minutes ago, and you can read about the API here: http://literallycanvas.com/api/tools.html

**Comment by 178620086** [comment]
very happy to know you released new version .
the new doc is very friendly .
thank for you .

**Comment by 178620086** [comment]
last the new api only sport v0.4.5?
and  we want to use v0.4.4 because we need the color select in left.

**Comment by irskep** [comment]
The nature of new software versions is that the old versions stay old.

I moved the color picker to the top/bottom because I think it works better there. Since I am (pretty much) the only one who works on this, I feel comfortable making design changes like that without consulting anyone or making it configurable. If you want to move it back, you are welcome to contribute a patch that makes it an option. Commit 9f54dd76 has the old code in it.

Given how ugly the old version looked (to my eyes), I'm surprised you want it back.

**Comment by 178620086** [comment]
because  if let color picker to top in Mobile devices is hard to use in my project.

**Comment by irskep** [comment]
So you're more interested in #240.

Adjusting the UI to fit better on phones doesn't require such drastic measures as moving the color picker back. I was planning to work on this problem in my next session in two weeks.

**Comment by 178620086** [comment]
ok. thank for you !
