### ISSUE TITLE
bug Pencil 

### ISSUE THREAD

**Issue by 178620086** [literallycanvas/literallycanvas#300]
where the line 4124
variable is call Pencil
but in 4190 also call Pencil
have two same name function
Although the two name is indicate Pencil and Polygon.
but i think this should have difference.
<pre lang="js">
function Pencil() {
    return Pencil.__super__.constructor.apply(this, arguments);
  }
</pre>

<pre lang="js">
var Pencil, ToolWithStroke, createShape,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ToolWithStroke = _dereq_('./base').ToolWithStroke;

createShape = _dereq_('../core/shapes').createShape;

module.exports = Pencil = (function(_super) {
  __extends(Pencil, _super);

  function Pencil() {
    return Pencil.__super__.constructor.apply(this, arguments);
  }

  Pencil.prototype.name = 'Pencil';

  Pencil.prototype.iconName = 'pencil';

  Pencil.prototype.eventTimeThreshold = 10;

  Pencil.prototype.begin = function(x, y, lc) {
    this.color = lc.getColor('primary');
    this.currentShape = this.makeShape();
    this.currentShape.addPoint(this.makePoint(x, y, lc));
    return this.lastEventTime = Date.now();
  };

  Pencil.prototype.continue = function(x, y, lc) {
    var timeDiff;
    timeDiff = Date.now() - this.lastEventTime;
    if (timeDiff > this.eventTimeThreshold) {
      this.lastEventTime += timeDiff;
      this.currentShape.addPoint(this.makePoint(x, y, lc));
      return lc.drawShapeInProgress(this.currentShape);
    }
  };

  Pencil.prototype.end = function(x, y, lc) {
    lc.saveShape(this.currentShape);
    return this.currentShape = void 0;
  };

  Pencil.prototype.makePoint = function(x, y, lc) {
    return createShape('Point', {
      x: x,
      y: y,
      size: this.strokeWidth,
      color: this.color
    });
  };

  Pencil.prototype.makeShape = function() {
    return createShape('LinePath');
  };

  return Pencil;

})(ToolWithStroke);

},{"../core/shapes":11,"./base":42}],39:[function(_dereq_,module,exports){
var Pencil, ToolWithStroke, createShape,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ToolWithStroke = _dereq_('./base').ToolWithStroke;

createShape = _dereq_('../core/shapes').createShape;

module.exports = Pencil = (function(_super) {
  __extends(Pencil, _super);

  function Pencil() {
    return Pencil.__super__.constructor.apply(this, arguments);
  }

  Pencil.prototype.name = 'Polygon';

  Pencil.prototype.iconName = 'polygon';

  Pencil.prototype.usesSimpleAPI = false;

  Pencil.prototype.didBecomeActive = function(lc) {
    var onDown, onMove, onUp, unsubscribeFuncs;
    unsubscribeFuncs = [];
    this.unsubscribe = (function(_this) {
      return function() {
        var func, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = unsubscribeFuncs.length; _i < _len; _i++) {
          func = unsubscribeFuncs[_i];
          console.info("func:"+func);
          _results.push(func());
        }
        return _results;
      };
    })(this);
    this.points = null;
    this.maybePoint = null;
    onUp = (function(_this) {
      return function() {
        if (_this._getWillClose()) {
          _this._close(lc);
          return;
        }
        if (_this.points) {
          _this.points.push(_this.maybePoint);
        } else {
          _this.points = [_this.maybePoint];
        }
        _this.maybePoint = {
          x: _this.maybePoint.x,
          y: _this.maybePoint.y
        };
        lc.setShapesInProgress(_this._getShapes(lc));
        return lc.repaintLayer('main');
      };
    })(this);
    onMove = (function(_this) {
      return function(_arg) {
        var x, y;
        x = _arg.x, y = _arg.y;
        if (_this.maybePoint) {
          _this.maybePoint.x = x;
          _this.maybePoint.y = y;
          lc.setShapesInProgress(_this._getShapes(lc));
          return lc.repaintLayer('main');
        }
      };
    })(this);
    onDown = (function(_this) {
      return function(_arg) {
        var x, y;
        x = _arg.x, y = _arg.y;
        _this.maybePoint = {
          x: x,
          y: y
        };
        lc.setShapesInProgress(_this._getShapes(lc));
        return lc.repaintLayer('main');
      };
    })(this);
    unsubscribeFuncs.push(lc.on('pointerdown', onDown));
    unsubscribeFuncs.push(lc.on('pointerdrag', onMove));
    unsubscribeFuncs.push(lc.on('pointermove', onMove));
    return unsubscribeFuncs.push(lc.on('pointerup', onUp));
  };

  Pencil.prototype.willBecomeInactive = function(lc) {
    return this.unsubscribe();
  };

  Pencil.prototype._getWillClose = function() {
    var firstPoint, lastPoint, mDist, testPoint, _i, _len, _ref;
    if (!(this.points && this.points.length > 2)) {
      return false;
    }
    if (!this.maybePoint) {
      return false;
    }
    firstPoint = this.points[0];
    lastPoint = this.points[this.points.length - 1];
    _ref = [firstPoint, lastPoint];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      testPoint = _ref[_i];
      mDist = Math.abs(this.maybePoint.x - testPoint.x) + Math.abs(this.maybePoint.y - testPoint.y);
      if (mDist < 10) {
        return true;
      }
    }
    return false;
  };

  Pencil.prototype._close = function(lc) {
    this.maybePoint = null;
    lc.setShapesInProgress([]);
    if (this.points.length > 2) {
      lc.saveShape(this._getShape(lc, false));
    }
    return this.points = null;
  };

  Pencil.prototype._getShapes = function(lc, isInProgress) {
    var shape;
    if (isInProgress == null) {
      isInProgress = true;
    }
    shape = this._getShape(lc, isInProgress);
    if (shape) {
      return [shape];
    } else {
      return [];
    }
  };

  Pencil.prototype._getShape = function(lc, isInProgress) {
    var points;
    if (isInProgress == null) {
      isInProgress = true;
    }
    points = [];
    if (this.points) {
      points = points.concat(this.points);
    }
    if ((!isInProgress) && points.length < 3) {
      return null;
    }
    if (isInProgress && this.maybePoint) {
      points.push(this.maybePoint);
    }
    if (points.length > 1) {
      return createShape('Polygon', {
        isClosed: this._getWillClose() || (!isInProgress),
        strokeColor: lc.getColor('primary'),
        fillColor: lc.getColor('secondary'),
        strokeWidth: this.strokeWidth,
        points: points.map(function(xy) {
          return createShape('Point', xy);
        })
      });
    } else {
      return null;
    }
  };

  return Pencil;
</pre>

thank you

**Comment by irskep** [comment]
You're looking at the generated JS, not the source, so this is irrelevant.

**Comment by 178620086** [comment]
ok  . close
