### ISSUE TITLE
Can't call lc.drawShapeInProgress() on an image

### ISSUE THREAD

**Issue by 178620086** [literallycanvas/literallycanvas#301]
I see the Api to create a Image
like 
<pre lang="js">
LC.createShape("Image",{image: img, x: demo.nowPt.x, y: demo.nowPt.y,scale:0.5});
</pre>
but return Object shape is no scale prop.
<pre>
Object {x: 391, y: 255, image: img, id: "e0a08212-0d88-2439-2a37-3799c55bbe65"}
</pre>
and in script also not to use scale 

<pre lang='js'>
defineCanvasRenderer('Image', function(ctx, shape, retryCallback) {
  if (shape.image.width) {
    console.info(shape);
    return ctx.drawImage(shape.image, shape.x, shape.y);
  } else if (retryCallback) {
    return shape.image.onload = retryCallback;
  }
});
</pre>
new find image shape is can not to use LC.drawShapeInProgress !!!
is not className?

this is a bug ?

**Comment by irskep** [comment]
Ah, the docs are incorrect.

I have only ever seriously tested images as backgrounds and never tried scaling. Will look at this for the next release.

**Comment by 178620086** [comment]
thank you 
but we need this function fast.
how can i fix the ?

**Comment by irskep** [comment]
Is it crashing or something? If so, please provide a test case that demonstrates it. Otherwise, you need to explain *why* you need this particular function implemented.

If your business depends on this project, it's up to you to help work on it. I do this for fun so I don't stick to anyone's deadlines.

**Comment by 178620086** [comment]
.....will 
i have been give up .

wo use a simple api to create a tools to insert a image .
simple use not case.
but insert a  big image is hard to see.

wait for you next a release.

**Comment by irskep** [comment]
Have you tried using setShapesInProgress() instead of drawShapeInProgress()?

**Comment by irskep** [comment]
Images in drawings present more complex challenges than other tools, which is why I haven't yet provided one. Dealing with images is inherently not simple.

**Comment by 178620086** [comment]
i use you project to create a Multiplayer sketchpad .

use nodejs and socket.io to transfor.

and the service install on android dirver

**Comment by 178620086** [comment]
yes ,i think so .

but time is less.
we can't wait .
so i create a simple tools to insert .

**Comment by 178620086** [comment]
Have you tried using setShapesInProgress() instead of drawShapeInProgress()?

i not have try .

wait

**Comment by 178620086** [comment]
i have try.
this lc.setShapesInProgress([image]);
have effect.
but also can't scaling.

**Comment by irskep** [comment]
This version of the library does not implement image scaling. It is not very hard to implement yourself.

**Comment by 178620086** [comment]
i use version is 0.4.4

i'm trying

**Comment by 178620086** [comment]
maybe not very hard .

but i not use cofficescript.
so it very hard .

**Comment by 178620086** [comment]
Use lc.setShapesInProgress([image]); 
image can not Real time draw on the canvas .
 why?

**Comment by irskep** [comment]
For everyone's reference, the demo page now includes a working implementation of an image tool, and the docs have been updated to be more correct.

https://github.com/literallycanvas/literallycanvas/blob/master/demo/index.html
