### ISSUE TITLE
my way to insert a image tools 

### ISSUE THREAD

**Issue by 178620086** [literallycanvas/literallycanvas#302]
bad code not to show...
wait my upload a demo

**Comment by 178620086** [comment]
oh,no  china GFW is ...

i'm not upload the project..

**Comment by 178620086** [comment]
why the new version 0.4.6 has not have Scaling？


。。。。

**Comment by irskep** [comment]
Because no one has ever implemented image scaling.

**Comment by 178620086** [comment]
you not want to do the first one?

**Comment by irskep** [comment]
I'm not going to immediately implement every feature request anyone asks for.

**Comment by 178620086** [comment]
will ,ok i wait for you good nows.

**Comment by irskep** [comment]
Since this is not a bug report or feature request, I am closing it.
