### ISSUE TITLE
image fromJson error char 'x' bug

### ISSUE THREAD

**Issue by 178620086** [literallycanvas/literallycanvas#307]
<pre lang="js">
  fromJSON: function(data) {
    var img;
    img = new Image();
    img.src = data.imageSrc;
    return createShape('Image', {
      x: data.x,
      x: data.y,
      image: img
    });
</pre>
double x.diff size!
fix 'x' to 'y'
<pre lang="js">
  fromJSON: function(data) {
    var img;
    img = new Image();
    img.src = data.imageSrc;
    return createShape('Image', {
      x: data.x,
      y: data.y,
      image: img
    });
</pre>

**Comment by irskep** [comment]
Fixed in master with 47337a613b059587c8f0d3bf26d5aea7d1653c90
