### ISSUE TITLE
Undo/Clear not triggered on open geometry path

### ISSUE THREAD

**Issue by lushfuture** [literallycanvas/literallycanvas#315]
Using the custom shape tool, if you don't "close" the path by clicking/tapping the start point, the shape persists on the canvas after clicking undo & clear buttons. Other shapes created before/after behave appropriately. "Open" path shape _does_ scale and translate with the zoom and move tools.

I've only checked Chrome on mobile & desktop, but I feel like this is probably an issue with internal state management in React component and not a browser-specific issue.

Google Chrome 44.0.2403.133 Mobile - Android 5.1.1
Google Chrome 44.0.2403.157 (64-bit) Desktop - OSX 10.10.4

**Comment by irskep** [comment]
The undo/redo thing is fixed in master. I'll handle clear as well.

The tool API doesn't handle this very well. My strategy for defining the tool API is to write enough tools to see a pattern, and then implement the pattern. The polygon and text tools are on the bleeding edge of this strategy.

**Comment by irskep** [comment]
What are you using Literally Canvas for, btw?

**Comment by lushfuture** [comment]
Oh, sorry I was just checking the demo page!

I'm not using it for anything in particular, just playing around in my search for canvas/react implementations. I have graphs to make and I'm trying to avoid SVG because of lots of datapoints. This project got me excited when I saw how well it actually worked

**Comment by irskep** [comment]
Canvas performance and React are unrelated. All canvas operations are done without any external libraries; only the wrapper UI is React. (just FYI)

**Comment by lushfuture** [comment]
Yup, I'm aware that React doesn't have anything to do with canvas performance. I'm building on top of an existing React application and it's interesting to see how people handle interfacing with canvas inside of a React application since it's inherently isolated from the rest of the DOM.

**Comment by irskep** [comment]
Yeah, the way I generally handle it is to have a "canvas controller" that you send events to from React callbacks or manual event bindings or whatever, and set it up/tear it down in the component mounting lifecycle methods. It works well.
