### ISSUE TITLE
How to put options button to tool picker bar

### ISSUE THREAD

**Issue by uparejiya** [literallycanvas/literallycanvas#316]
Can anyone please tell me how to put all options button like strokewidth, dashed line, arrow, etc. to Tool Picker bar?

Please reply fast.

**Comment by irskep** [comment]
In short, you can't. No one has implemented an API for that.

**Comment by irskep** [comment]
Anyone who wants to do this should probably just use the [core build](http://literallycanvas.com/installing.html#skipping-the-gui-and-the-react-dependency), so I'm closing this issue.
