### ISSUE TITLE
The shape object sent to the shapeSave event is unable to be added back via the saveShape method

### ISSUE THREAD

**Issue by bikegriffith** [literallycanvas/literallycanvas#325]
I want to subscribe to the `shapeSave` event and then render changes into a second canvas as a mirror.

```
lcOne.on('shapeSave', function(args) {
  lcTwo.saveShape(args.shape, false, args.previousShapeId)
});
```

Trying this throws the following exception:

```
Uncaught Can't render shape of type undefined to canvas
```

I've tried manually setting the className, but it doesn't appear to help.  Am I thinking about this wrong or is there a bug?

**Comment by irskep** [comment]
Interesting. I'll look into this. What is the output of LC.shapeToJSON(shape)?

**Comment by bikegriffith** [comment]
Hmm, just tried to reproduce in a tiny example and it does appear to be working now.  I'm going to see if I did something else silly in my larger example.

**Comment by bikegriffith** [comment]
It's working now; my bad.  When I was sending over the wire, I didn't call `LC.shapeToJSON` and `LC.JSONToShape` appropriately.
