### ISSUE TITLE
Allow resizing image shapes

### ISSUE THREAD

**Issue by jatinseth2007** [literallycanvas/literallycanvas#327]
Hi Team,

I need to set a background Image of the drawing board and make it responsive too. I am able to set background Image at run time by using API function LC.createShape() but need to set the Height and Width of the image.

Need Suggestion !!

**Comment by irskep** [comment]
There is currently no way to do this without defining your own custom image shape and renderer. This is planned for the next release, but I can't guarantee a release date for the work.

It is certainly possible (and not very hard) to define your own custom image shape and the corresponding canvas renderer.

Relevant docs:

http://literallycanvas.com/api/shapes.html#defining-shapes

Original image shape code (in CoffeeScript, unfortunately, but easy to translate):

* https://github.com/literallycanvas/literallycanvas/blob/master/src/core/shapes.coffee#L118
* https://github.com/literallycanvas/literallycanvas/blob/master/src/core/canvasRenderer.coffee#L99

If you're feeling particularly generous, you could submit a pull request.

**Comment by jboullion** [comment]
This is not a perfect fix, but might help others in the future who have this issue like I did.

I could not get background images to do what I wanted, but I was able to use a regular image shape and set it as he first element which emulates a background image, and those can be scaled like so.

```
scale = 1
if(lc.canvas.width < defaultWidth || lc.canvas.height < defaultHeight){
	//which dimension has the greatest difference and scale based on that
	if( (lc.canvas.width / defaultWidth) < (lc.canvas.height / defaultHeight) ){
		scale *= (lc.canvas.width / defaultWidth).toFixed(3);
	}else{
		scale *= (lc.canvas.height / defaultHeight).toFixed(3);
	}
}

//attempt to adjust the annotation wrapper to match the scaled image size
document.getElementById('annotation').style.width = Math.ceil(scale * wrapperWidth) +'px';

//this will be the new background
backgroundImageObj = LC.createShape('Image', {x: 0, y: 0, image: img, scale: scale});

//apply the shape to the canvas
lc.saveShape(backgroundImageObj);
```
