### ISSUE TITLE
Eraser option not displayed correctly

### ISSUE THREAD

**Issue by zazics** [literallycanvas/literallycanvas#331]
Hello,
When I choose eraser, the size in option panel is not set (visually) correctly. To reproduce it:
1) select Pencil
2) select the biggest size (in option panel)
3) select Eraser >> the size selected (visually) is the biggest one while the size used effectively is default one.

If you click on Eraser once again, then the right one is selected visually.

**Comment by irskep** [comment]
Thanks for the report with clear repro steps. I'll fix it in the next release.

**Comment by christianheimann** [comment]
Just to say, this bug concernes also the other tools:
1. select Pencil
2. select the biggest size (in option panel)
3. select rectangle tool: option panel will highlight biggest size. draw rectangle: stroke width will be default
4. select circle tool: option panel will highlight default size. draw circle: stroke width will be default.
5. without changing circle tool: change to biggest size.
6. select again rectangle tool: option panel will highlight biggest size. draw rectangle: stroke width will be default
7. select again circle tool: option panel will highlight default size. draw circle: stroke width will be «biggest»
Thank you for having a look at it.

**Comment by irskep** [comment]
Have you tried the current development build? I think I fixed this a few weeks ago, but haven't released it yet.

You'll have to build the JS yourself to try it, or I can do it if you have trouble.

**Comment by zazics** [comment]
No, I didn't try it. I can wait next release.
