### ISSUE TITLE
Background image loading in Safari/Webkit and Xulrunner

### ISSUE THREAD

**Issue by christianheimann** [literallycanvas/literallycanvas#334]
Using literallycanvas in an _eclipse RCP application_ on _Mac_, I had the problem that the when I load literallycanvas and initialize the editor with a background image, this **background image was not displayed.** Our workaround changes with a mousemove trigger the size of the window container, then the background image appears.
It seems to be a safari/webkit issue, that there is no event fired when the image is loaded. Workarounds like described under [Javascript Image onload doesn't fire in webkit – StackOverflow](http://stackoverflow.com/questions/5024111/javascript-image-onload-doesnt-fire-in-webkit-if-loading-same-image) do not work.
Unfortunately also on _Windows_ this behaviour appears within _Xulrunner_ used in _RCP_.

The size of the image may affect this behaviour – in our case the images had a size of approx. 2000 x 1000 px, they were not only 5 kb patterns …

Is there any solution in sight or another workaround recommended?

**Comment by irskep** [comment]
Are you setting `image.onload`? If so, try using `LC.util.addImageOnload()` instead: http://literallycanvas.com/api/util.html#LC.util.addImageOnload

The reason is that Literally Canvas needs to attach additional image load handlers to correctly re-render after images load.

**Comment by irskep** [comment]
(That might not help at all, but I do need to check.)

**Comment by christianheimann** [comment]
I checked the addImageOnload, but the callback keeps coming too early with addImageOnload.

But, in a new created html with literally canvas, also opening in a RCP browser instance, this mentionned problem did not (re)appear. So I cannot tell you more about the origin of this problem, think we can close this issue.
