### ISSUE TITLE
JSONToShape not work

### ISSUE THREAD

**Issue by masoud5098** [literallycanvas/literallycanvas#335]
i must be create shape with json
i get json shape with this command : 

<code> var a = lc.getSnapshot(); </code>
<code> var b = a1.shapes[0]; </code>
<code> var c = LC.JSONToShape(b) </code>

but not draw <b>b</b> Object

I try This But Not Work
In contineu I first Draw A Shape And Get Json And clear Page And Run This
<code>var Strt = '{';</code>
<code>$.each (b.data , function(key , val) { Strt += key+':"'+val+'",' } );</code>
<code>var str = Strt.substr(0,(Strt.length-1));</code>
<code>str += '}';</code>
<code>var x = 'LC.createShape("'+b.className+'" , '+str+')'; </code>
My String This : 
<code>
LC.createShape("Rectangle" , {x:"603",y:"65",width:"-162",height:"100",strokeWidth:"5",strokeColor:"#000",fillColor:"#fff"})
 </code>
and Eval This String 
Response Object TO me But No Drawing

Tank You

**Comment by irskep** [comment]
Why are you using eval at all?

**Comment by irskep** [comment]
Also, in your initial example, what is the output of `JSON.stringify(b)`?

**Comment by masoud5098** [comment]
ok , i have Hard Day for solution to this problem.
And Tanks irskep , May Be My Description Not Good. 
But the solution : 
You get snapShot , Get Latest Shape , Convert TO Json And Send  Json to Other Machine
in reciver System convert Json to Shape , and <b>Save This </b>

<code> var a = lc.getSnapshot();  </code>
<code> var len = a.shapes.length;   len--; </code>
<code> var b = a.shapes[len] </code>
<code> var c = JSON.stringify(b) </code>
Now Send C 
On the Reciver System Run This
<code> var d = JSON.parse(c) </code>
<code> var e = LC.JSONToShape(d) </code>
<code> lc.saveShape(e,true,null) </code>

Have Good Day And Good Luck

**Comment by irskep** [comment]
Again, I can't really help you unless you provide the string you are trying to parse.

**Comment by irskep** [comment]
Closing due to lack of info; reopen if you can provide what I asked for
