### ISSUE TITLE
Typeo in svgRenderer.coffee

### ISSUE THREAD

**Issue by wansco** [literallycanvas/literallycanvas#339]
The stroke-width needs a space after the preceding quote.

https://github.com/literallycanvas/literallycanvas/blob/cf41d8fe371874ccbb800a82194f0d3ae2f15439/src/core/svgRenderer.coffee#L90

**Comment by wansco** [comment]
And line 92 should close the g tag (i.e. </g>):

https://github.com/literallycanvas/literallycanvas/blob/cf41d8fe371874ccbb800a82194f0d3ae2f15439/src/core/svgRenderer.coffee#L92

**Comment by irskep** [comment]
Fixed in 0.4.11.

**Comment by wansco** [comment]
Looks like the typeo is still there:
stroke='#{shape.co**lor} 'str**oke-width='#{shape.strokeWidth}'
should be
stroke='#{shape.co**lor}' str**oke-width='#{shape.strokeWidth}'

Great project, by the way

**Comment by irskep** [comment]
Damn.

**Comment by wansco** [comment]
Hahaha, no worries. Its easily fixed in the compiled code.
