### ISSUE TITLE
«Negative» SVG Shapes 

### ISSUE THREAD

**Issue by christianheimann** [literallycanvas/literallycanvas#342]
SVG from the function LC.renderSnapshotToSVG(this.lc.getSnapshot()); do contain rectangle and ellipse shapes with negative width/heights respectively negative rx/ry values, when they are drawn from «right to left/down to up».

> The svg specification says that if width or height are negative then the rectangle is not drawn.
Read http://stackoverflow.com/questions/15597368/is-it-possible-to-set-negative-width-in-svg-rectangle. 

So SVG are not giving the correct result e.g. when displaying in a browser.

**Comment by irskep** [comment]
Good catch, thanks.

**Comment by irskep** [comment]
Fixed in 0.4.11.
