### ISSUE TITLE
Error: Converting circular structure to JSON

### ISSUE THREAD

**Issue by christianheimann** [literallycanvas/literallycanvas#343]
Using literallycanvas on Android, we get a 
> Error: Converting circular structure to JSON

when we call JSON.stringify(this.lc.getSnapshot()); On Webkit/Firefox it works fine.

Does anyone know this issue?

**Comment by christianheimann** [comment]
This happened, when we inserted a JSON object at initialisation of editor with a «primary, secondary and background color» object. It seemed to be create this error on Android. But the exact problem was not found.

**Comment by christianheimann** [comment]
We were able to restrain this error: on Android Browser <= 4.4, the function JSON.stringify(this.lc.getSnapshot()) returns the Error.
In Android >= 5.0 it works.

**Comment by irskep** [comment]
I don't think this is a bug in the project. You should try looking at the contents of `lc.getSnapshot()` to find the cycle, and then maybe reopen with a more definite bug.
