### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by justinhunt** [literallycanvas/literallycanvas#344]
I can't get LiterallyCanvas to load via AMD.  The issue, I think (though I am not positive) is the loading of the React dependency. It is declared as a dependency on the module that I use to load LiterallyCanvas.  

But it fails with the following message. 
" Can't find React (you need the version with addons)"
The version of React (with add ons ) is the most recent 0.14.3 from here: https://facebook.github.io/react/downloads.html

The top line of my AMD module looks like this:
define(['jquery','core/log', 'filter_poodll/utils', 'filter_poodll/react-with-addons', 'filter_poodll/literallycanvas'], function($, log, utils, React, LC) {

Is this a known issue, or am I just doing something wrong?

**Comment by irskep** [comment]
React needs to be installed on `window.React`. I realize this may violate many people's sense of justice, but that's the way it is. I would accept a pull request to fix it.

**Comment by justinhunt** [comment]
It takes a lot to violate my sense of justice. I happily installed React on window.js and that solved it for me. I would dive into the code, and I guess I will eventually because I love LC. But I really haven't the time now to set up a js dev environment and get to grips with the js build tools you use. I am a simple PHP drone I guess.

For anyone else who needs to do this. I created a file called react_amd.js . Its most interesting dependency is the react-with-addons.min.js distributable. react_amd.js looks like this:

define(['jquery','core/log', 'filter_poodll/react-with-addons'], function($, log, React) {
  "use strict"; 
  log.debug('react initialising');
  window.React = React;
  return {}
});

Then this became a dependency to script I use to initialize literally canvas, the top part of which looks like this:

define(['jquery','core/log', 'filter_poodll/utils_amd', 'filter_poodll/react_amd', 'filter_poodll/literallycanvas'], function($, log, utils, React, LC) {

    "use strict"; // jshint ;_;

    log.debug('Filter PoodLL: literallycanvas.js initialising');
...

**Comment by irskep** [comment]
I believe pull request #364 fixes this.

**Comment by irskep** [comment]
(Or rather, it was fixed before, but #364 fixes bugs related to it.)

**Comment by justinhunt** [comment]
Great and thanks. Its stable and working for me now having installed it on window.react. 
But I will pull the latest release soon and spend a bit of time integrating it properly

**Comment by irskep** [comment]
Tested and working.

**Comment by irskep** [comment]
(With CommonJS, not AMD, I should say. I'm actually not entirely sure what the difference is...)

**Comment by irskep** [comment]
OK, I did my research, and I did not implement AMD at all. (Honestly I don't really have plans to, but always accepting patches...) I'll make a separate ticket for CommonJS.

**Comment by justinhunt** [comment]
OK. But it does load and run as an AMD module using the method you
initially advised (installing react on window.react).
I will have to wrap some much simpler libraries up as AMD modules soon.
Once I have gone through that process, perhaps I can come back and give it
a try here.

**Comment by irskep** [comment]
Going forward I only care about whether this is installable via npm, and if the import system is ever changed it will be to ES6 imports.
