### ISSUE TITLE
Text rotation?

### ISSUE THREAD

**Issue by teaearlgraycold** [literallycanvas/literallycanvas#345]
Given how the Text tool uses a textarea when rendered it should be simple enough to rotate it with CSS.

**Comment by irskep** [comment]
I've never seen a rotated editable text box in a web browser, ever.

**Comment by teaearlgraycold** [comment]
Get ready to have your mind blown: https://jsfiddle.net/k8smufru/.

Tested it in Firefox and Chrome. Both work perfectly - and the rotation styles should support IE back all the way to 9.

Image manipulation programs typically allow you to write text vertically, so it seems a reasonable addition to LiterallyCanvas.

**Comment by irskep** [comment]
Covered by #365
