### ISSUE TITLE
Direct usage as React component?

### ISSUE THREAD

**Issue by idolize** [literallycanvas/literallycanvas#355]
Very cool project! I am actually using React in my entire app, and I was hoping to use literallycanavs directly without having to jump out of the React virtual DOM (as shown in the README: `LC.init(document.getElementsByClassName('literally without-jquery')[0])`).

(It's cool that you've provided a nice wrapper around React for people not already using it, but in my case it would actually make my life easier to avoid the wrapping :smile:)

Would it be possible for me to just `require` `'literallycanvas/reactGUI/Picker'` and `'literallycanavas/reactGUI/Options'` and instantiate them inside my `render()` method directly? I guess I'd have to transpile the coffeescript too.

I.e., instead of using the [wrapped `React.render()` calls here](https://github.com/literallycanvas/literallycanvas/blob/master/src/reactGUI/init.coffee#L16), just write `<Picker />` and `<Options /> `in my JSX.

Would this work? If so, I think it'd be nice to have documented as another official "entry point" for the library.

**Comment by irskep** [comment]
I actually have a similar problem in my own project, drawplz.com. I punted by doing this:

```coffee
lc = null
LiterallyCanvas = React.createClass
  displayName: 'LiterallyCanvas'
  getDefaultProps: -> {drawing: null}
  componentDidMount: ->
    lc = LC.init(this.getDOMNode())
    window.debugLC = lcWrapper.lc
  render: -> <div className="literally" />
```

I can't think of a good way to expose the React API, because of this question: how do you know when to re-render? Subscribe to every single documented event? That sounds fragile.

**Comment by idolize** [comment]
How is that determined currently? Typically with React components you get an automatic re-render of the component whenever the `state` or `props` change (and `shouldComponentUpdate()` returns `true`). If you are reacting to updates that aren't reflected in `props` or `state` you can get around this with [`forceUpdate()`](https://facebook.github.io/react/docs/component-api.html#forceupdate) to force a re-render.

**Comment by irskep** [comment]
The various React components subscribe themselves to events on `lc` and update their own state. So to answer my own question, you wouldn't have to determine it at all. So I retract the question. :-)

Followup question: how would you bootstrap it? You'd essentially have to have the user of the library duplicate this code: https://github.com/literallycanvas/literallycanvas/blob/master/src/reactGUI/init.coffee

**Comment by irskep** [comment]
(In case it isn't obvious: right now I am in the mode of parachuting in to answer questions but don't have the state of the project in my brain most of the time, so some of my questions or comments might be silly. I will usually realize the mistake at some point.0

**Comment by idolize** [comment]
Yeah, I know how that is when you haven't been working on a codebase in a while, so don't sweat it. I appreciate you taking the time to help on something you probably aren't even using yourself right now anyway.

-----

As far as your question: my recommendation would be to think about what the core required initialization parameters are that you need from the developer, and make those the props required for the "bootstrapping" component (maybe that would be the existing `<Picker>` and `<Options>` components, or maybe you would want to wrap those in a "higher order component").

The rest of the boilerplate, like this stuff:

```coffeescript
toolButtonComponents = tools.map (ToolClass) ->
  toolInstance = new ToolClass(lc)
  createToolButton
    displayName: toolInstance.name
    imageName: toolInstance.iconName
    getTool: -> toolInstance
```

could probably go inside the `componentDidMount` section, like you show above (although it's a bit ugly it should work).

If you wanted to make things a bit more React-ish, you could look at removing the `createToolButton` factory stuff and just do the `tools.map()` bit directly inside of `Picker`'s `render()` method.

From the [React docs](https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html):

> Don't worry about precomputing values based on state — it's easier to ensure that your UI is consistent if you do all computation within render(). For example, if you have an array of list items in state and you want to render the count as a string, simply render this.state.listItems.length + ' list items' in your render() method rather than storing it on state.

**Comment by idolize** [comment]
I started working on this, but have been struggling mostly because I have never worked with Coffeescript before and find the syntax confusing (especially without JSX).

**Anyway, I believe it should be relatively simple to create a wrapped React component that can be used directly to do all the initialization currently in `index.coffee` (including creating the `LiterallyCanvas` instance) while still maintaining backwards-compatibility with the existing API for non-React users.**

Right now, all `index.coffee` seems to really do is parse the options (which can be passed as `props`), create the instance of `LiterallyCanavs`, and render the React components for `Picker` and `Options`. The only part of this which is hard to do in a React component is the second part (create the `LiterallyCanvas` instance, which requires creating/manipulating DOM nodes directly).

What I would do is break this down into a top-level `<LiterallyCanavs>` component, which has a `render` method that looks (approximately) like the following:

```js
return (
  <div>
    <CanvasContainer ref="canvas" />
    <Picker />
    <Options />
  </div>
);
```

Now, instead of having to do all this stuff:

```js
drawingViewElement = document.createElement('div');
drawingViewElement.className = 'lc-drawing with-gui';
el.appendChild(drawingViewElement);

pickerElement = document.createElement('div');
pickerElement.className = 'lc-picker';

optionsElement = document.createElement('div');
optionsElement.className = 'lc-options horz-toolbar';

el.appendChild(pickerElement);
el.appendChild(optionsElement);
```

React will take care of that for us.

Creating the Tools is likewise very simple:

```js
const { tools } = this.props; // set defaults in getDefaultProps()
const toolButtonComponents = tools.map(ToolClass => {
  const toolInstance = new ToolClass(lc);
  return createToolButton({
    displayName: toolInstance.name,
    imageName: toolInstance.iconName,
    getTool: () => toolInstance
  });
});
```

Ok, so now we have this as the `render` method for `<LiterallyCanvas>`:

```js
const { tools, imageURLPrefix } = this.props; // set defaults in getDefaultProps()
const toolButtonComponents = tools.map(ToolClass => {
  const toolInstance = new ToolClass(lc);
  return createToolButton({
    displayName: toolInstance.name,
    imageName: toolInstance.iconName,
    getTool: () => toolInstance
  });
});

// TODO: Missing 'lc' instance! Still incomplete :(

const pickerProps = { lc, toolButtonComponents, imageURLPrefix };
return (
  <div>
    <CanvasContainer ref="canvas" />
    <Picker {...pickerProps} />
    <Options lc={lc} imageURLPrefix={imageURLPrefix} />
  </div>
);
```

But, in order to create an instance of `LiterallyCanavs` we need to point it to an *already-existing* DOM element for it to take control over and create the `<canvas>`, etc. Rather than try to React-ify that part of the codebase (there isn't much point anyway since using React effectively with the `<canvas>` API is largely impossible), I would just use the `ref` from the `CanvasContainer` (which is really just a `<div>`) with [`findDOMNode`](https://facebook.github.io/react/docs/working-with-the-browser.html#refs-and-finddomnode) to break out of the React VDOM.

I imagine that would look something like this:

```js
var CanvasContainer = React.createClass({
  displayName: 'CanvasContainer',
  shouldComponentUpdate() {
    // Avoid React trying to control this DOM
    return false;
  },
  render() {
    return (
      <div key="literallycanvas" className="lc-drawing with-gui" />
    );
  }
})

var LiterallyCanvas = React.createClass({
  displayName: 'LiterallyCanvas',
  getDefaultProps() {
    return {
      imageURLPrefix: '../img/',
      primaryColor: 'hsla(0, 0%, 0%, 1)',
      secondaryColor: 'hsla(0, 0%, 100%, 1)',
      backgroundColor: 'transparent',
      strokeWidths: [1, 2, 5, 10, 20, 30],
      defaultStrokeWidth: 5,
      toolbarPosition: 'top',
      keyboardShortcuts: true,
      imageSize: {width: 'infinite', height: 'infinite'},
      backgroundShapes: [],
      watermarkImage: null,
      watermarkScale: 1,
      zoomMin: 0.2,
      zoomMax: 4.0,
      zoomStep: 0.2,
      snapshot: null
    }
  },
  componentDidUpdate() {
    if (!this.lc && this.refs.canvas) {
      const canvasContainerDom = findDOMNode(this.refs.canvas);
      const opts = this.props;
      // Create the LC instance now that we have the DOM node reference
      // (Takes two render() cycles to complete)
      this.lc = new LiterallyCanvas(canvasContainerDom, opts);
    }
  },
  componentWillUnmount() {
    if (this.lc) {
      // No need to remove the DOM nodes anymore since React takes care of that
      this.lc.teardown();
    }
  },
  render() {
    const { lc, props } = this;
    const { tools, imageURLPrefix } = props; // get defaults from getDefaultProps()
    const toolButtonComponents = tools.map(ToolClass => {
      const toolInstance = new ToolClass(lc);
      return createToolButton({
        displayName: toolInstance.name,
        imageName: toolInstance.iconName,
        getTool: () => toolInstance
      });
    });
    const pickerProps = { lc, toolButtonComponents, imageURLPrefix };
    return (
      <div>
        <CanvasContainer ref="canvas" />
        { lc &&
          <Picker {...pickerProps} />
        }
        { lc &&
          <Options lc={lc} imageURLPrefix={imageURLPrefix} />
        }
      </div>
    );
  }
});
```

------

@irskep how hard would it be to convert this to Coffeescript?

**Comment by irskep** [comment]
Actually, I would ask how hard it would be to add a JSX file to the project! I want to move away from Coffeescript anyway. I think you could add a JSX/ES6 transformer to the build chain pretty easily.

**Comment by irskep** [comment]
I just skimmed over your comment and it looks correct. If you have time to add JSX+ES6 to the build config and implement your changes, I would be happy to pull them. Otherwise I will leave this here for future reference when I eventually(...) get time to work on this.

**Comment by idolize** [comment]
Sure thing! I'm in the process of getting it working for me locally. Not quite working ("options" not showing up), but getting close!

![screen shot 2016-01-12 at 3 38 25 pm](https://cloud.githubusercontent.com/assets/635005/12280459/e823af66-b942-11e5-8ba4-0e42b4641c4c.png)

**Comment by idolize** [comment]
I got it working in #358. The only downside is I couldn't keep the API exactly as-is. If that is an issue, it should still be possible, but you'll have to maintain two different codepaths (one with the old initialization code from index.coffee, and one for initialization via the wrapper React component).

Please take a look and let me know what you think!

**Comment by idolize** [comment]
@irskep Have you had a chance to look at the updated code? Thanks :)
