### ISSUE TITLE
Eraser option causes a shift in option panel

### ISSUE THREAD

**Issue by zazics** [literallycanvas/literallycanvas#359]
When I select "eraser" then a size option, the size I've clicked on is not selected. I have to click twice. To reproduce it:
1. click on "Eraser". Size level 3 is selected by default
2. select size level 4 ==> nothing changes
3. select size level 5 ==> this is size level 4 that is selected (the previous one)
4. select size level 1 ==> this is size level 5 that is selected(the previous one)
5. Change to "Pencil" ==> same problem in size panel
6. Change to "Line" ==> everything becomes good.

**Comment by irskep** [comment]
This should have been fixed in v0.4.11, released a few weeks ago. What version are you using?

**Comment by zazics** [comment]
I've just installed and tested the last one (0.4.11). This issue is not the same as issue #331 . It's a new strange behaviour.

**Comment by irskep** [comment]
Fixed in master, to be released today or this weekend.
