### ISSUE TITLE
Undo is broken in master (canvas doesn't redraw properly)

### ISSUE THREAD

**Issue by irskep** [literallycanvas/literallycanvas#366]

**Comment by irskep** [comment]
@MandaBrown I think this was caused by your commit 32e89182d10bb4fffe8fadc5d76563911641d8bf. Could you explain why you made the change?

**Comment by irskep** [comment]
Fixed by reverting 32e8918.

**Comment by MandaBrown** [comment]
Ugh, it made sense to me at the time. I am very sorry. :(

**Comment by irskep** [comment]
It's OK, you made the change in a small commit so it was really easy to revert.

**Comment by irskep** [comment]
The canvas rendering code is pretty obtuse so I'm not surprised that the "correct-looking" version isn't actually correct.
