### ISSUE TITLE
Additional shapes

### ISSUE THREAD

**Issue by dwelch2344** [literallycanvas/literallycanvas#37]
First off, let me just say this looks awesome. Just discovered this via Twitter but love what I'm seeing. Great work!

One feature I think would be awesome would be additional shapes similar to what Google Drive's Drawing feature has. If I get some extra time I'll even try to add / contribute what I can. 

Thanks!

**Comment by irskep** [comment]
This issue is too vague. If people want specific shapes, they should be created as individual tickets. I'll add a ticket for a polygon tool myself.
