### ISSUE TITLE
onInit callback is no longer working?

### ISSUE THREAD

**Issue by lideen** [literallycanvas/literallycanvas#380]
It seems like the onInit callback is no longer called when literally is initialized with jquery (after upgrading from 0.4.11 to 0.4.13).

A minimal example: https://plnkr.co/edit/ThMfqwzWaJbBjCPxXtzV?p=preview

Tested on Google Chrome Version 47.0.2526.106 (64-bit)

**Comment by irskep** [comment]
Thanks for providing a minimal example. I can't promise when I'll look into this (currently in the process of packing and moving) but a fix will be in the next release.

**Comment by irskep** [comment]
I am "solving" this by removing the jQuery plugin from the next version. I don't want to support it anymore.

**Comment by irskep** [comment]
However, this bug affected more than just the jQuery plugin, and I just implemented the fix.
