### ISSUE TITLE
Mailing list doesnt work

### ISSUE THREAD

**Issue by mwechter** [literallycanvas/literallycanvas#381]
Steve
I have sent multiple emails to the literalycanvas@librelist and never got a response nor have any of my posts shown up.
What is the best way to contact you?

**Comment by irskep** [comment]
Argh, I'm so sorry about this. It's been broken for a while. I need to find another solution. For now just open GH issues even if it seems inappropriate. I'll try to update the docs and read me soon.

**Comment by irskep** [comment]
I just set up a new mailing list in a more reliable place: https://groups.google.com/forum/#!forum/literallycanvas
