### ISSUE TITLE
Saved image bit depth and scaling

### ISSUE THREAD

**Issue by mwechter** [literallycanvas/literallycanvas#388]
Steve
These two issues might be tied together.
I am loading onto the canvas a converted tiff image 2545x3320 **bit depth 1**. When I save the image
lc.getImage().toDataURL() I get a bit depth 32. The image files are considerably larger. Is there a way to stay as a pure b/w image?
When I get them back they are also scaled down by some 30%.
I tried setting setZoom to 1 before the getImage but that did not seem to resolve the issue.

Thanks

**Comment by irskep** [comment]
I don't think this is something JS has control over. Browser image export APIs are very rudimentary afaik.

**Comment by mwechter** [comment]
Is there a way to declare a canvas as only B/W ?

*Michael Wechter*
Michael@AdaptiveVoice.com
949.436.7760

**Comment by irskep** [comment]
I don't think so. Either way, I'm not going to be a great source of information for issues like this.
