### ISSUE TITLE
Docs don't explain how to set size of widget

### ISSUE THREAD

**Issue by alephman** [literallycanvas/literallycanvas#389]
steve,
is there a way to scale the whole literallycanvas?  It looks be fixed size(555*400 with gui) when it's initialised.

**Comment by sblackstone** [comment]
Looking for an answer to this as well..

**Comment by sblackstone** [comment]
I'm trying to use literallycanvas embedded in another project, and I'd like to have the editor bounds be the same as the image bounds and let the screen scroll rather than make the user pan..

**Comment by sblackstone** [comment]
NM - I see you can set the height on the original DOM element and that is respected..

**Comment by irskep** [comment]
@sblackstone is correct. I think that used to be really obvious from the docs, but I can't find it now. Changing this to a docs issue.

**Comment by irskep** [comment]
Added a blurb to the Initializing page.
