### ISSUE TITLE
Drawing tools draw with a 20 pixel shift to the right

### ISSUE THREAD

**Issue by etcsayeghr** [literallycanvas/literallycanvas#392]
Hi there, I am using LiterallyCanvas 0.4.13 as downloaded from the website, and I used the example code, however I am finding that when I use a drawing tool the drawing actually occurs around 20 pixels (a guess) to the right of where the mouse icon is. Help?

**Comment by etcsayeghr** [comment]
Attached is my literally canvas example code.

[literallycanvas.zip](https://github.com/literallycanvas/literallycanvas/files/198191/literallycanvas.zip)

**Comment by irskep** [comment]
You followed the instructions correctly; trouble is, the instructions were wrong. See #399. Just rename your container class and you should be good to go. Sorry about this.
