### ISSUE TITLE
How to delete shapes programmatically?

### ISSUE THREAD

**Issue by think123** [literallycanvas/literallycanvas#398]
Is there a way to delete a shape programmatically? I've looked at the API, maybe not thoroughly enough, but is there a way for me to do this?

**Comment by collectingideas** [comment]
Same question.

**Comment by think123** [comment]
I figured out how to do it (kind of) - you'll need to copy in the following code into your `literallycanvas` JavaScript file. Put it underneath `LiterallyCanvas.prototype.clear`:

```
LiterallyCanvas.prototype.rerender = function(newShapes) {
    var oldShapes;
    oldShapes = this.shapes;
    this.setShapesInProgress([]);
    this.execute(new actions.ClearAction(this, oldShapes, newShapes), false);
    this.repaintLayer('main');
  };
```

Then you'll just need to write something like:

`lc.rerender(shapes);`

Where `shapes` is a shape object containing all your shapes.
