### ISSUE TITLE
container class name can NOT be "literally"

### ISSUE THREAD

**Issue by godwin668** [literallycanvas/literallycanvas#399]
I followed instructions of
http://literallycanvas.com/installing.html#classic-style

But does NOT work.

I found the problem line is:
&lt;div class="literally"&gt;&lt;/div&gt;

When I change the div class name from "literally" to other name, it works.

**Comment by irskep** [comment]
Interesting, thanks for the report. I'll try to fix in the next release. I bet it's a code issue rather than documentation.

**Comment by sunsetsystems** [comment]
Glad I saw this!  Was tearing my hair out, then changed the class name from "literally" to "notliterally" and it started working.

**Comment by irskep** [comment]
I spent some time with the code and determined that having people rename the outer class is the cleanest solution. ReactDOM.render() doesn't let you render to the element you passed, only its children.

Updating the docs now.
