### ISSUE TITLE
How to change the stroke width when using the core build?

### ISSUE THREAD

**Issue by IanBeaubien** [literallycanvas/literallycanvas#400]
Hi, thanks a lot for this well made widget. I'm using the core build with my own ui using most of the default tools. I'm trying to change the stroke width but can't seem to make it work. 

thanks

**Comment by IanBeaubien** [comment]
Ok I managed to update the strokeWidth. I was trying to update the value of the object instead of the tool itself. But now, i can draw with the selected stroke, but as soon as I mouse up, the stroke is back to 5 px.

**Comment by IanBeaubien** [comment]
It's only doing that for pencil and eraser

**Comment by IanBeaubien** [comment]
Ok after investigating, the behavior for pencil or eraser differs from let's line. 
If I set let the stroke with right after init like `var pen = new LC.tools.Pencil(lc);
        pen.strokeWidth = 3;` it works perfectly. Then if I try to updat ethe strokeWidth afterwards like `activeTool.tool.strokeWidth = 7;` it behaves strangely. It draws at 1 px, then on end, it draaws back to 3px.

**Comment by IanBeaubien** [comment]
@irskep any way to get help on this? I'm stuck.

**Comment by irskep** [comment]
Honestly I don't have time to look into this right now. I do think people have gotten this to work in the past. You might try looking for other users of the core build in the list of closed pull requests and in issue comments. Sorry I can't be more helpful at the moment.

**Comment by rorysmorris** [comment]
Calling this works for me. 

`lc.trigger('setStrokeWidth', 50);`

**Comment by irskep** [comment]
I just tried `lc.tool.strokeWidth = blah` and it worked fine. Link me to a complete example if it's still a problem.
