### ISSUE TITLE
How to remove instance?

### ISSUE THREAD

**Issue by bowenjbl** [literallycanvas/literallycanvas#402]
I want to remove the instance of the plugin when i close a modal popup, when i download the canvas image using lc.getImage().toDataURL(), the previous canvas and the new canvas show in the console log, the teardown function give me this error **Cannot read property 'willBecomeInactive' of null**

**Comment by irskep** [comment]
Can't debug without a full stack trace or complete example. Reopen if you can provide either.

**Comment by irskep** [comment]
(I have an idea and will put a null guard in teardown() for the tool in the next release.)
