### ISSUE TITLE
React demo doesn't work right

### ISSUE THREAD

**Issue by DexterHaslem** [literallycanvas/literallycanvas#403]
I followed instructions from https://github.com/literallycanvas/literallycanvas-demos/tree/master/npm_webpack_react after experiencing issues in a large react app. It doesn't appear to be drawing right - stroke & fill bg end up as text and stroke width is outside of the window.
I made the issue here because I did not see anything obviously wrong with the demo. here is a screenshot

![image](https://cloud.githubusercontent.com/assets/370456/15300552/74323e20-1b66-11e6-8675-772d34766320.png)

**Comment by DexterHaslem** [comment]
Figured it out.. using the css: 'node_modules/literallycanvas/css/literallycanvas.css' results in above. however using the css file _assets/literallycanvas.css like the classic_ examples works fine.

**Comment by irskep** [comment]
Great find! Thanks so much for digging into this.

I guess the answer is that I need to put the correct CSS into the package. But I should update the docs in the meantime. (As you can probably tell, the time I have to spend on this project is now very very small.)

**Comment by DexterHaslem** [comment]
no worries! would you like a pull request? Is that the right CSS to distrobute if so?

**Comment by irskep** [comment]
Actually, no, because I don't recognize that path. The right thing to do is probably ask people to download and include the CSS separately.

I could be convinced otherwise, it's just my instinct.

**Comment by irskep** [comment]
Specifically, this file: https://github.com/literallycanvas/literallycanvas/blob/release/css/literallycanvas.css

If that works for you, that should probably be the recommendation (substituting 'release' for 'v4.1.13')

**Comment by DexterHaslem** [comment]
I dropped that version of the file in and tried classic_with_gui example again and it went completely bonkers, the canvas immediately resized to 262188px tall and it looked like this
![image](https://cloud.githubusercontent.com/assets/370456/15302959/c808cb8e-1b72-11e6-833b-e03f6b29580e.png)

Just to be clear, the only css that has worked for me is this specific CSS - https://github.com/literallycanvas/literallycanvas-demos/blob/master/_assets/literallycanvas.css

**Comment by irskep** [comment]
Ah. So I should just do a new release because clearly I have messed up the CSS packaging pretty badly.

**Comment by DexterHaslem** [comment]
Haha, well the examples on the site worked fine so I didn't give up!

**Comment by irskep** [comment]
Looked into this some more. The canonical CSS location should actually be `node_modules/literallycanvas/lib/css/literallycanvas.css`. The existence of a 'css' directory in the top level of the package is a bug.

Does that work better?

**Comment by irskep** [comment]
Verified myself, this seems to work. Updating the examples to do the same.

**Comment by DexterHaslem** [comment]
Great, thank you!
