### ISSUE TITLE
React component looking for non-existent image

### ISSUE THREAD

**Issue by DexterHaslem** [literallycanvas/literallycanvas#404]
If you click on stroke or fill you get this error in console

`   DOMPropertyOperations.js:159 GET http://localhost:9005/images/checkerboard-8x8.png 404 (Not   Found)`

it seems to be coming from here

https://github.com/literallycanvas/literallycanvas/blob/2f27c1dfec9af46579f596dee53973399a7f3d7e/src/reactGUI/ColorWell.coffee#L182

I assume the file doesn't exist? Or was it forgotten somewhere

**Comment by irskep** [comment]
Looks like you never set imageURLPrefix.

**Comment by irskep** [comment]
Or you never added the images to your server.

**Comment by DexterHaslem** [comment]
I did both. For example the canvas on http://literallycanvas.com/index.html also throws the error. Doesn't seem to impact anything from what I can tell though

**Comment by irskep** [comment]
Oh, fun, that image is just missing. You can pull it out of /lib/img/ in this repo.
