### ISSUE TITLE
After resizing the canvas with setImageSize, the panning tool does not work anymore

### ISSUE THREAD

**Issue by parkroolucas** [literallycanvas/literallycanvas#405]
I'm using this to set the pan tool, which is working in all cases:

`lc.setTool(new LC.tools.Pan(lc));`

Except for after I resize the canvas with setImageSize.

I tested with the given examples in Literally Canvas, and it doesn't work there either.

Can this be fixed?

**Comment by irskep** [comment]
I can't really debug this without a complete example. I just tried panning, resizing, and panning, and it worked.
