### ISSUE TITLE
Default tools set

### ISSUE THREAD

**Issue by Perfect7M** [literallycanvas/literallycanvas#407]
How to change default tools set.
I didn't saw any function in api to manage that except `lc.defaultTools();` but i don't know how to use it.
I don't want to have Polygon and for example Elipse tool. How can i do that? 

I change literarycanvas.js and delete some tools in `tools` object but its not affected
```
tools = {
  Pencil: require('./tools/Pencil'),
  Eraser: require('./tools/Eraser'),
  SelectShape: require('./tools/SelectShape'),
  Tool: baseTools.Tool,
  ToolWithStroke: baseTools.ToolWithStroke
};
```

**Comment by irskep** [comment]
There is no way to change the default tool set, but the way to change the tools is documented here. http:/literallycanvas.com/api/initializing.html
