### ISSUE TITLE
Clipping Region

### ISSUE THREAD

**Issue by michaelaguiar** [literallycanvas/literallycanvas#416]
Is it possible to set a drawing region?  For example, I have a T Shirt image I am using for the background.  I don't want to be able to draw outside of that t shirt.

Please let me know if I missed something in the docs, or if there is an issue with this!

**Comment by irskep** [comment]
Did something actually happen or did you just close this?

**Comment by michaelaguiar** [comment]
Oh yea I actually figured out a way to do it a while back and realized I still had this open.
