### ISSUE TITLE
Bug: Localization not working for tooltips

### ISSUE THREAD

**Issue by sunsetsystems** [literallycanvas/literallycanvas#417]
It appears LC.localize() has no effect for the tooltips text.

Oh and thanks for the fantastic widget!  We will be using it with the OpenEMR project on SourceForge.

Rod

**Comment by irskep** [comment]
Thanks for the report. Should be easy to fix, if anyone wants to go in and take care of it.

AFAIK the localization stuff is completely untested. I have no translation files to test with. It's in there just in case it happens to work. :-)

**Comment by irskep** [comment]
I'm pretty sure this was fixed in 0.4.something. Please feel free to reopen if that's not the case.

**Comment by irskep** [comment]
Oh, and if you have a translation, it would be great to contribute it so others can benefit!
