### ISSUE TITLE
How to create lasso and erase content inside it

### ISSUE THREAD

**Issue by nguyenhiep2906** [literallycanvas/literallycanvas#419]
I want erase a path of image like lasso in photoshop.
Can you tell me how to do it ?
Thanks

**Comment by irskep** [comment]
The two minute answer is about as helpful as [this classic image](https://s-media-cache-ak0.pinimg.com/564x/75/4a/1d/754a1def902e9d60cbd631184106d883.jpg):

1. Read the API for creating tools
2. Create the tool

The only other answer is the 30 minute answer, which would explain how to implement it in about 8 hours.

**Comment by irskep** [comment]
Closing this because either someone will make this tool, or they won't. I don't have time to do a long explanation for it.
