### ISSUE TITLE
Export to SVG - erasures

### ISSUE THREAD

**Issue by DonBooth** [literallycanvas/literallycanvas#422]
lc.getSVGString();
Does not include erasures. 
Is this possible?

Much thanks,

Don Booth

**Comment by irskep** [comment]
No, the SVG format does not allow this. (If you can find docs to the contrary and link them there, I would be happy to be wrong.)

**Comment by DonBooth** [comment]
Much thanks, Steve.

I thought I’d ask but I assumed it just was not possible.

If you could do this then you would have, more or less, Illustrator in the browser.

You wrote a very nice editor.

Thank you,

Don Booth

**Comment by DonBooth** [comment]
Hi Steve,

The following is beyond my abilities to implement but you might find it of interest:
https://www.w3.org/TR/SVG/masking.html#Masking <https://www.w3.org/TR/SVG/masking.html#Masking>

In short, if I follow the example correctly, we define an svg element as a mask and then apply that mask to another element.

I have not looked at your code so I have no idea if this might be applicable.

best,

Don Booth

**Comment by irskep** [comment]
Good find. Yeah, you could use that to implement the eraser in SVG. I had just been looking at drawing modes for paths before.
