### ISSUE TITLE
How to resize canvas to the size of Background Image

### ISSUE THREAD

**Issue by krnaveen14** [literallycanvas/literallycanvas#424]
I've added a background image as

```
var img = new Image();
img.src = 'img/1.png';

var options = {
      // Make Transparent fill
      secondaryColor : 'hsla(0, 0%, 100%, 0)',
      backgroundShapes : [LC.createShape('Image', {x: 0, y: 0, image: img})]
};

var lc = LC.init(document.getElementsByClassName('literally core')[0], options);
```

By default, the canvas has min-height of 400px as defined in LC css and width is of entire screen width. I need to resize the canvas to exactly the height and width of Background image.

If BG image is 700 x 392, I need my canvas to be of 700 x 392 (width & height respectively). I can't seem to find any API's to achieve this.

Am I missing any available API or this have to controlled manually by getting the width & height of image (in image onload callback) and then restricting canvas size to that size..?

**Comment by AndySedeyn** [comment]
I do it myself:
```JavaScript
$(function() {
	// Get the width and height
	var w = backgroundImage.width;
	var h = backgroundImage.height;
	var child_canvas = document.getElementsByTagName("canvas");
	// Set the width and height attributes of all the canvas to that of the picture
	for(var i = 0, j = child_canvas.length; i < j; i++) {
		child_canvas[i].setAttribute("width", (w + "px"));
		child_canvas[i].setAttribute("height", (h + "px"));
	}
	// Set the width and height of the canvas
	$(".lc-drawing").css({'height': h, 'width': w});
	$(".lc-drawing > canvas").css({'height': h, 'width': w});

	/*
	*	Not making these calculations will make the image come out of the canvas by +20px.
	*	That is because the css of the area where the image is put in is: top:0px and left:0px
	*	To fix this we have to add the width of the side toolbar and the height of the top toolbar to that area
	*/

	var lc_picker_width = document.getElementsByClassName("lc-picker")[0].offsetWidth;
	var horz_toolbar_height = document.getElementsByClassName("horz-toolbar")[0].offsetHeight;
	var tool_width = w + lc_picker_width;
	var tool_height = h + horz_toolbar_height;
	$(".toolbar-at-top").css({'height': tool_height,'width': tool_width });
	$(".lc-picker").css({'height': (h + horz_toolbar_height) }); // Changing (h + horz_toolbar_height) to tool_height caused an error on "$(document)".
	$(".horz-toolbar").css({'width': w });
});
```
Not setting the width/height attributes of the canvas element will cause the image to stretch. Also, using onload will cause the image to stay hidden until the user manually resizes the window.

I'm sure my snippet can be optimised, but I'm not big on JavaScript myself, so excuse me for it.

**Comment by jboullion** [comment]
This is not a perfect fix, but might help others in the future who have this issue like I did.

I could not get background images to do what I wanted, but I was able to use a regular image shape and set it as he first element which emulates a background image, and those can be scaled like so.

`
scale = 1
if(lc.canvas.width < defaultWidth || lc.canvas.height < defaultHeight){
	//which dimension has the greatest difference and scale based on that
	if( (lc.canvas.width / defaultWidth) < (lc.canvas.height / defaultHeight) ){
		scale *= (lc.canvas.width / defaultWidth).toFixed(3);
	}else{
		scale *= (lc.canvas.height / defaultHeight).toFixed(3);
	}
}

//attempt to adjust the annotation wrapper to match the scaled image size
document.getElementById('annotation').style.width = Math.ceil(scale * 1180) +'px';

//this will be the new background
backgroundImageObj = LC.createShape('Image', {x: 0, y: 0, image: img, scale: scale});

//apply the shape to the canvas
lc.saveShape(backgroundImageObj);
`
