### ISSUE TITLE
Update PeerDependencies of React

### ISSUE THREAD

**Issue by zhaoyao91** [literallycanvas/literallycanvas#427]
The React versions should be updated in peerDependencies.

**Comment by markboyall** [comment]
We cannot update to React 15.4.2 as LiterallyCanvas specifies 15.1.

**Comment by irskep** [comment]
I don't plan to do this upgrade myself. Should be easy for anyone to
submit a patch. I will test and merge.




On Wed, Jan 11, 2017, at 06:35 AM, Mark Boyall wrote:

> We cannot update to React 15.4.2 as LiterallyCanvas specifies 15.1.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 




Links:

  1. https://github.com/literallycanvas/literallycanvas/issues/427#issuecomment-271869811

**Comment by irskep** [comment]
Done as of 0.5.0
