### ISSUE TITLE
Warning: Unknown prop

### ISSUE THREAD

**Issue by zhaoyao91** [literallycanvas/literallycanvas#428]
I have got the following warnings with react 15.3.0
![image](https://cloud.githubusercontent.com/assets/3808838/17458693/707e8180-5c4d-11e6-865f-d26148349682.png)

**Comment by eko24ive** [comment]
@irskep any updates on this one ?

**Comment by irskep** [comment]
Looks like a recent version of React changed the API or something. I don't have time to fix it.

**Comment by lapcchan** [comment]
no plan on supporting latest react version?

**Comment by irskep** [comment]
I will be happy to do a release if someone submits a pull request with the necessary changes.

**Comment by irskep** [comment]
This is probably fixed in 0.5.0, which supports React 16.

**Comment by eko24ive** [comment]
"probably" :D
