### ISSUE TITLE
exporting with toDataURL() produces a file that cannot be opened..

### ISSUE THREAD

**Issue by raident30** [literallycanvas/literallycanvas#430]
hi i was trying to export literally canvas image using these codes using codeigniter:

```
$('.controls.export-bounded [data-action=export-as-png]')
	    .click(function(e) {
	      e.preventDefault();
	    
	      $.post('<?php echo site_url('fapplication/export_pdf'); ?>', { data: lc.getImage().toDataURL() }, function () {
	        
	      });               
	    });
```

	
```
public function export_pdf()
{
	$data = base64_decode($_POST["data"]);

	$fname = time();
	$dir = "./uploads/cq_requirements/temp/".$fname.".png";
	file_put_contents($dir, $data);
}
```

but all it produces was a 6.48kb file that cannot be opened. I tried not using code igniter with these codes but they work just fine. are there any incompatibility with codeigniter?

**Comment by irskep** [comment]
I don't know what the hell codeigniter is, but it's 100% not a literally canvas issue. You or the framework is probably mangling the data URL somewhere.

Also, you're trying to base64-decode the "data:" prefix, which you shouldn't do.
