### ISSUE TITLE
Load/Save Background 

### ISSUE THREAD

**Issue by Hammadeh** [literallycanvas/literallycanvas#434]
Thank you very much i am using Literallycanvas with Gui Demo,but i cannot find out how can set background to drawing board, i mean i want load background from base64,then i want to save it with the drawing shapes on it as a base64 string , can you help me with that :) thank you very much

**Comment by Ghost141** [comment]
Same requirement here.

**Comment by irskep** [comment]
Background shapes are already included in snapshots. Is that somehow not working?

```js
const bgImage = new Image();
bgImage.src = // YOUR DATA URL
const lc = LC.init(el, {backgroundShapes: /* the image shape */});
lc.getSnapshot()  // this contains the background image shape
```
