### ISSUE TITLE
setLineDash - Module is not defined

### ISSUE THREAD

**Issue by Tywin3** [literallycanvas/literallycanvas#435]
Hi there!

I've been using Literally Canvas to make a picture editing plugin alongside the abillity to copy paste images from the clipboard.

Locally on my PC it's working fine.

I went on to include the project via Grails and to launch it locally then using my test server and I've come to a couple of errors.
![image](https://cloud.githubusercontent.com/assets/22769098/19269708/6cde33fc-8fbc-11e6-95bd-1a66c722d418.png)

First error is according to the code : 
module.export=null.

And the second has something to do with index.js.

I've added my HTML code and my custom scripts. What is really weird is that it works with no errors locally, and when I add it here it's all gone haywire.

Do help ! :)

**Comment by irskep** [comment]
This sounds like a problem with your build system, unrelated to this project. I do not currently have time to help you sort it out.
