### ISSUE TITLE
optionsStyle: 'stroke-width' is not working.

### ISSUE THREAD

**Issue by ivanisrael** [literallycanvas/literallycanvas#441]
var MyTool = function(lc) {  // take lc as constructor arg
  var self = this;

  return {
    usesSimpleAPI: false,  // DO NOT FORGET THIS!!!
    name: 'MyTool',
    iconName: 'line',
    strokeWidth: lc.opts.defaultStrokeWidth,
    optionsStyle: 'stroke-width',

    didBecomeActive: function(lc) {
      var onPointerDown = function(pt) {
        self.currentShape = LC.createShape('Line', {
          x1: pt.x, y1: pt.y, x2: pt.x, y2: pt.y,
          self.strokeWidth, color: lc.getColor('primary')});
        lc.setShapesInProgress([self.currentShape]);
        lc.repaintLayer('main');
      };

      var onPointerDrag = function(pt) {
        self.currentShape.x2 = pt.x;
        self.currentShape.y2 = pt.y;
        lc.setShapesInProgress([self.currentShape]);
        lc.repaintLayer('main');
      };

      var onPointerUp = function(pt) {
        self.currentShape.x2 = pt.x;
        self.currentShape.y2 = pt.y;
        lc.setShapesInProgress([]);
        lc.saveShape(self.currentShape);
      };

      var onPointerMove = function(pt) {
        console.log("Mouse moved to", pt);
      };

      // lc.on() returns a function that unsubscribes us. capture it.
      self.unsubscribeFuncs = [
        lc.on('lc-pointerdown', onPointerDown),
        lc.on('lc-pointerdrag', onPointerDrag),
        lc.on('lc-pointerup', onPointerUp),
        lc.on('lc-pointermove', onPointerMove)
      ];
    },

    willBecomeInactive: function(lc) {
      // call all the unsubscribe functions
      self.unsubscribeFuncs.map(function(f) { f() });
    }
  }
};

LC.init(el, {
  // Add me to the toolbar
  tools: LC.defaultTools.concat([MyTool])
});

----------------------------------------------------------------------------------------------------------

Above is the sample from the site, when using it, the option to change the stroke width does not work.

**Comment by irskep** [comment]
I'm pretty sure this was just fixed in 0.5.0. I had transplanted a space character, which made some SVG invalid.
