### ISSUE TITLE
Diff between lc.undo() and lc.on( 'undo', ... )

### ISSUE THREAD

**Issue by erdonmez** [literallycanvas/literallycanvas#444]
Hi LC Lovers,

I am trying to figure out the diff between lc.undo() and lc.on( 'undo', .. ) events.

What I'm doing is something like;

lc.on( 'undo', function(){
  console.log( 'This is because you click the undo button' );
} )

if ( shaple.x > 333 ) {
  console.log( 'Since your drawing is larger than 333, it will be ignored!' );
  lc.undo();
}

But when I draw something larger than 333, then it logs both messages.

Can anyone help me to distinguish ?

Thanks in Advance.

**Comment by erdonmez** [comment]
For those who have already faced this problem or will face this problem, here is a trick;

Instead of lc.undo()

That can be used;
lc.shapes[i].remove()
lc.undoStack[i].remove()

But, I am still open to different solutions.

**Comment by irskep** [comment]
Well, the `undo` event fires when you `undo()`, so of course if you call `lc.undo()` then your undo handler will fire too. This is not a bug.
