### ISSUE TITLE
setShapesInProgress linePath shape bug

### ISSUE THREAD

**Issue by frankywen** [literallycanvas/literallycanvas#451]
[gist with code](https://gist.github.com/irskep/b316ba6dbd084e5247388c6e7a68fed6)

![image](https://cloud.githubusercontent.com/assets/9948618/22738729/95f0c558-ee43-11e6-8ad5-743a976735ff.png)

i can't see the linePath or line shape 
but i see the linePath shape when mouse down and move
when mouse up those disappear

![image](https://cloud.githubusercontent.com/assets/9948618/22739047/e3b138da-ee44-11e6-86cf-03e2674aa1d1.png)

**Comment by irskep** [comment]
This seems like it might be a real bug, but I can't understand what's going on. You should not be using `setShapesInProgress` in normal usage unless you are implementing custom tools.
