### ISSUE TITLE
Questions and feature requests

### ISSUE THREAD

**Issue by berserk82** [literallycanvas/literallycanvas#460]
Hello there.
My name is Ivano Arrighetta and I'm Italian.
I have 2 questions about literallycanvas:
1) How is the browser support?
2) Can it be used locally (without a server or a framework)?

And some feature requests:
brush - with blending modes
lines and splines - with style (dashed, dotted, thickness, cap, join, etc)
crop
cage transform
translate/rotate/scale
offset
layers - with blending modes, can be entyre images
selection - lasso, magic wand, by color - with invert, add and substract
alpha masking
alpha blending
text - following a path or filling a shape
flood fill - with color, gradient, texture
erase
clone
color adjustments - hue, saturation, brightness, contrast, white balance
stroke - with style
align and distribute objects
interpolate lines - with style
shapes
filters
can save an image

Thanks in advance for any help.

Bye, Ivano.

**Comment by irskep** [comment]
The answers to your questions can be found in the documentation. The feature requests do not belong in one big ticket.

**Comment by berserk82** [comment]
Thanks, I found answer to my questions in the docs.
How do I submit feature requests then?

**Comment by irskep** [comment]
One per ticket, preferably with comprehensive descriptions.

I should say, though, there are currently _zero_ people working actively on this project. I just still answer tickets because they go to my email.

**Comment by berserk82** [comment]
Ok, could you suggest me a more actively developed alternative?

**Comment by irskep** [comment]
No, that is what's so sad! :-) This barely-maintained project is still better than anything else out there, it just needs someone who cares about it and has time to become active.
