### ISSUE TITLE
Cannot make viewing area as tall as background image

### ISSUE THREAD

**Issue by jaschahal** [literallycanvas/literallycanvas#464]
```
backgroundImage = new Image();
        backgroundImage.src = "/imagecdn/test.jpg"; // image width:800px; height: 5000px;
        backgroundImage.onload = function() {
            height = backgroundImage.height;
            width = backgroundImage.width;
            LCeL = document.getElementsByClassName('my-drawing')[0];
            var lc = LC.init(
                LCeL,
                {
                    imageURLPrefix: "/js/lcanvas/img",
                    backgroundShapes: [
                        LC.createShape(
                            'Image', {x: 10, y: 10, image: backgroundImage, scale: 1})
                    ],
                    tools: [
                        LC.tools.Pencil,
                        LC.tools.Eraser,
                        LC.tools.Line,
                        LC.tools.Rectangle,
                        LC.tools.Text,
                        LC.tools.Polygon,
                        LC.tools.Pan
                    ],
                    imageSize: {width: width+20, height: 5000},
                    onInit:function(){                     
                    }
                }
            );
```
Issue is that default height of 369 pixels, and other part of the image is hidden.
I am stumped, Could you please shed some light? Perhaps something I am missing which is straight forward.

**Comment by irskep** [comment]
Can't you just set the size of LC with CSS?


On Fri, Jul 7, 2017, at 05:41 PM, Jaspreet Chahal wrote:
> `backgroundImage = new Image();
>  backgroundImage.src = "/imagecdn/test.jpg"; // image width:800px; height: 5000px;>  backgroundImage.onload = function() {


>         height = backgroundImage.height; width =
>         backgroundImage.width; LCeL = document.getElementsByClassName('my-
>         drawing')[0]; var lc = LC.init( LCeL, { imageURLPrefix:
>         "/js/lcanvas/img", backgroundShapes: [ LC.createShape(
>         'Image', {x: 10, y: 10, image: backgroundImage, scale: 1}) ],
>         tools: [ LC.tools.Pencil, LC.tools.Eraser, LC.tools.Line,
>         LC.tools.Rectangle, LC.tools.Text, LC.tools.Polygon,
>         LC.tools.Pan ], imageSize: {width: width+20, height: 5000},
>         onInit:function(){  }  } );`
>> Issue is that default height of 369 pixels, and other part of the image is hidden.>  I am stumped, Could you please shed some light? Perhaps something I am missing which is straight forward.> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2]. > 


Links:

  1. https://github.com/literallycanvas/literallycanvas/issues/464

**Comment by jaschahal** [comment]
Yeah so true, Just checked out the code in details, seems like a simple thing to do.
Thanks for quick response

**Comment by beastlike** [comment]
Do you have an example of how to do this? When I apply it to the div, through CSS or style, it just makes the div larger without the drawing editor expanding:
```
<style>
    .drawing {
        border: 2px solid purple;
        width: 900px;
        height: 700px;
    }
</style>

<div class="drawing" >

</div>

<script>
var lc = LC.init(document.getElementsByClassName("drawing")[0], {
                imageSize: { width: 900, height: 700 },
                imageURLPrefix: '/img',
                toolbarPosition: 'bottom',
                primaryColor: "#f00",
                secondaryColor: "#000",
                defaultStrokeWidth: 2,
                strokeWidths: [1, 2, 3],
                backgroundColor: "#fff",
                tools: [
                    LC.tools.Pencil,
                    LC.tools.Eraser                   
                ]
            });
</script>
```

![image](https://user-images.githubusercontent.com/8137927/30129098-d47912a2-9312-11e7-9d12-e9aec5092df5.png)

**Comment by beastlike** [comment]
For those like me who couldn't figure it out:
 ```
   .literally {
        width: 900px;
        height: 700px;
    }
```
