### ISSUE TITLE
Enable literallycanvas to work with together.js

### ISSUE THREAD

**Issue by chillaz** [literallycanvas/literallycanvas#468]
I would like to ask if possible for Literally Canvas to be able to work with together.js. I am not a coder. Three years retired from teaching high school biology who is now creating a Web application for public schools. I believe Literally Canvas being able to work with together.js (https://togetherjs.com/) is an ideal tool to be used in public schools. I have a working example already done (http://demo.isessioner.com/online_whiteboard.php) but it doesn't work with together.js. I could have sworn it was working initially... I understand from together.js you can create an app.js to include it to make this happen. Marcelo Ricardo de Oliveira did this for his Web application Pixelreka at https://www.codeproject.com/Articles/700528/Pixelreka-Real-Time-Game-with-TogetherJS-JavaScrip, which gives anyone an idea of how its done.

**Comment by irskep** [comment]
Literally Canvas is not well built for realtime multi-user scenarios. If it were, this would be more appropriate for an independent project.
