### ISSUE TITLE
xss vulnerability when using text tool

### ISSUE THREAD

**Issue by rafaelchiti** [literallycanvas/literallycanvas#476]
It seems I can execute js when using the text tool, is there a way of escaping the text through an event before we 'render' it? 
To reproduce go to http://literallycanvas.com/index.html select the text tool, type `><img src=x onerror=alert("hello")>` and touch somewhere else in the drawing panel.

Thanks!!

**Comment by irskep** [comment]
Thanks so much for the report! I'll look into it this week.

**Comment by rafaelchiti** [comment]
@irskep hey, sorry for bugging you again, but wondering if I can help you out to speed up the fix, I sort of need to deliver a patch to our users with this fix soonish, anything I can do? I imagine we wanna change the Text Renderer but not sure from a library stand point how you want to react.

**Comment by irskep** [comment]
The problem is `src/core/fontmetrics.js`, a third party library I vendored in. It sets `innerHTML` of an orphan `div` without escaping anything.

The fix is to [HTML-escape](https://stackoverflow.com/questions/6234773/can-i-escape-html-special-chars-in-javascript) every call to `measureTextWidth` in `TextRenderer.coffee`.

I don't have time to do it myself for a few days though.

**Comment by irskep** [comment]
Or even better, monkey patch `measureTextWidth` to do the escaping itself.

**Comment by rafaelchiti** [comment]
I've tried quickly the two approaches yesterday, but no luck.


1. Tried patching the measureTextWidth inside fontmetrics.js (https://github.com/literallycanvas/literallycanvas/blob/master/src/core/fontmetrics.js#L48)

<img width="779" alt="screen shot 2017-12-12 at 10 13 43 am" src="https://user-images.githubusercontent.com/1154663/33886390-33402614-df25-11e7-839e-26dfe349cc95.png">




2. Tried escaping the text on each call to 'measure' in the file TextRenderer.coffee 
* https://github.com/literallycanvas/literallycanvas/blob/master/src/core/TextRenderer.coffee#L43
* https://github.com/literallycanvas/literallycanvas/blob/master/src/core/TextRenderer.coffee#L101


When trying '1' I get the same as without patching it. 
When trying '2' it only fails when I click outside the text editing field (when doing `><img src=x onerror=alert(1)>` I get only one alert when the last render happens), seems like I'm missing another instance of rendering where I'm not escaping the text, I'll need to spend more time and understand a bit better what's going on, will update if I find something.

Thanks for the help!

**Comment by irskep** [comment]
For option 1, it looks like you're not replacing the function, you're
defining a new one. (You create measureTextWidth, but wrap measureText.)
You need to replace it so that TextRenderer calls your patched version
instead of the original.

On Tue, Dec 12, 2017, at 05:21 AM, Rafael wrote:
> I've tried quickly the two approaches yesterday, but no luck.


>  1. Tried patching the measureTextWidth inside fontmetrics.js
>     (https://github.com/literallycanvas/literallycanvas/blob/master/src/core/fontmetrics.js#L48)> screen shot 2017-12-12 at 10 13 43 am


>  1. Tried escaping the text on each call to 'measure' in the file
>     TextRenderer.coffee
>  * https://github.com/literallycanvas/literallycanvas/blob/master/src/core/TextRenderer.coffee#L43
>  * https://github.com/literallycanvas/literallycanvas/blob/master/src/core/TextRenderer.coffee#L101> When trying '1' I get the same as without patching it.
>  When trying '2' it only fails when I click outside the text editing
>  field (when doing ><img src=x onerror=alert(1)> I get only one alert
>  when the last render happens), seems like I'm missing another
>  instance of rendering where I'm not escaping the text, I'll need to
>  spend more time and understand a bit better what's going on, will
>  update if I find something.> Thanks for the help!


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/literallycanvas/literallycanvas/issues/476#issuecomment-351049330

**Comment by attritionorg** [comment]
"The problem is src/core/fontmetrics.js, a third party library I vendored in." <- Can you clarify which library that is?

**Comment by irskep** [comment]
fontmetrics.js is itself the library.


On Tue, Dec 12, 2017, at 12:36 PM, Jericho wrote:
> "The problem is src/core/fontmetrics.js, a third party library I
> vendored in." <- Can you clarify which library that is?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/literallycanvas/literallycanvas/issues/476#issuecomment-351186294

**Comment by irskep** [comment]
@rafaelchiti please check out the referenced PR, #478, and verify that it's fixed. I could only make it happen intermittently when I reproduced the issue originally so it would be great to get some corroboration.

**Comment by rafaelchiti** [comment]
Hey! sorry for the delay. Tried that PR and it happens the same I mentioned in my case "2". Basically it works well until you click 'outside' the text editing area and it performs the final render in the canvas. It does fixes all the other instances though there is only one instance now where it parses the html and errors.

Here the simple text you can use to try it out `><img src=x onerror=alert(1)>`.

**Comment by irskep** [comment]
Really fixed now. It was the SVG code. It would actually generate an SVG string that would run the code, and then insert the SVG string directly into the DOM.

**Comment by rafaelchiti** [comment]
sorry for the delay. Just tested it on the branch, all working great!! thanks!.

**Comment by rafaelchiti** [comment]
@irskep any plans on delivering a release soon?
