### ISSUE TITLE
Error while adding literally canvas in react

### ISSUE THREAD

**Issue by bibudha** [literallycanvas/literallycanvas#482]
Hello

I got this error http://prntscr.com/hu4zua while applying literallycanvas in react project.
Its a kind of 
Warning: Unknown prop `float` on <label> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in label (created by ColorWell)
    in div (created by ColorWell)
    in ColorWell (created by ColorPickers)
    in div (created by ColorPickers)
    in ColorPickers (created by Picker)
    in div (created by Picker)
    in div (created by Picker)
    in div (created by Picker)
    in Picker (created by LiterallyCanvas)
    in div (created by LiterallyCanvas)
    in LiterallyCanvas

**Comment by irskep** [comment]
Not enough info, please provide a complete example. I doubt this is the library's fault or nothing would work at all.

**Comment by paction** [comment]
I have the same issue. The same two warnings:
```
react-dom.js?_cache=p08gqx:18137 Warning: Unknown prop `float` on <label> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

Warning: Unknown prop `viewPort` on <svg> tag. Remove this prop from the element.
```

Information about this issue from Reactjs ([https://reactjs.org/warnings/unknown-prop.html](https://reactjs.org/warnings/unknown-prop.html)):

> The unknown-prop warning will fire if you attempt to render a DOM element with a prop that is not recognized by React as a legal DOM attribute/property. You should ensure that your DOM elements do not have spurious props floating around.
