### ISSUE TITLE
How do you prepare releases?

### ISSUE THREAD

**Issue by rafaelchiti** [literallycanvas/literallycanvas#483]
Hey @irskep from what I understood (based on the ticket https://github.com/literallycanvas/literallycanvas/issues/480) it could take a while before a new release gets delivered. First of all, sorry for the annoyance, I understand you got trap in between being responsible of keeping the lib up to date and deciding how to spend your free time, it sucks. 

Basically I'm trying to understand how do you prepare the 'releases' so I can fork the library meanwhile and prepare a 14.5 with the XSS fix that our company needs. Do you run any script for releasing ? or could you share the manual process you do? so I can safely do the same in our fork.

Thanks!!

**Comment by irskep** [comment]
I just released 0.5.0, but here's the release process in case someone needs to mirror in an emergency:

```sh
# update git
gulp
npm publish
make release-branch # this makes the standalone builds and pushes them to github
```

If you need to publish under an alternate name because my releases aren't fast enough, just change the name of the package in `package.json` and `npm login` with your own credentials.

**Comment by rafaelchiti** [comment]
Sweet, thanks man!

**Comment by irskep** [comment]
If you rely on this library for a business, you might want me to just add you as a maintainer. :-) Shoot me an email if that sounds appealing.

**Comment by irskep** [comment]
BTW I skipped the step where I update all the documentation which is a whole other thing.

**Comment by rafaelchiti** [comment]
Hey man, sorry for the late response, I've been trying to find someone but we are sort of directed to other priorities at the moment :( 
I have not knowledge of the lib at all, but if another issue comes along with literally canvas and I end up bugging you again then I guess I might end up trying to help out and ask you for maintainer access.

Really appreciate your help and dedication! (and patience)
