### ISSUE TITLE
Set background Image Size

### ISSUE THREAD

**Issue by tuckerjt07** [literallycanvas/literallycanvas#488]
Is there a way to set the size of the background image before adding to to the canvas?

This works perfectly ```ctx.drawImage(backgroundImage, 0, 0, backgroundImage.width, backgroundImage.height, 0, 0, lc.canvas.width, lc.canvas.height); ``` except it's not a background image.

**Comment by tuckerjt07** [comment]
I was able to accomplish this by placing the canvas initialization inside of a setTimeout to delay the initalization, getting the size of the image and the canvas and then setting the scale to the smaller of the height width percentage pairs calculated from the above sizes.

**Comment by steve-cahn** [comment]
Did anyone get an answer to this? I'm trying to add an image after the canvas is initialized, and after the user does some drawing, but I want to set a max width to the image,
