### ISSUE TITLE
Memory usage increases dramatically when loading snapshots for multiple times

### ISSUE THREAD

**Issue by martianyi** [literallycanvas/literallycanvas#492]
Because undoStack is not cleaned up, memory usage will increase dramatically on Chrome if you call loadSnapshot for multiple times. 
Possible fix is set undoStack to empty in loadSnapshot method.
```
loadSnapshot: (snapshot) ->
     // ...
    if snapshot.shapes
      @shapes = []
      @undoStack = []
    // ...
```

**Comment by anx-ckreuzberger** [comment]
This is not a memory leak (per definition [1]), just some unintended behaviour.

But to be fair, resetting ``@undoStack`` (maybe by doing ``@undoStack.length = 0`` in loadSnapshot is a good idea. I guess when you load a (new) snapshot, you want the ``undoStack`` to be empty.

If you want, I can make a PR for that.

[1] Wikipedia says: In computer science, a memory leak is a type of resource leak that occurs when a computer program incorrectly manages memory allocations in such a way that memory which is no longer needed is not released.

``undoStack`` is still needed and accessed by literally canvas. The unintended behaviour is that ``undoStack`` still contains content from previous snapshots.

**Comment by martianyi** [comment]
@anx-ckreuzberger Thank you for your reply. Yes it's not a memory leak, sorry for my misspeaking, I updated the title, hope it describes the problem more properly.
I think it's a good idea to reset undoStack when load a new snapshot. I appreciate it if you can make a PR.

**Comment by irskep** [comment]
Yep, if someone sends a PR for this I'll happily merge it. Thanks for the investigation!

**Comment by anx-ckreuzberger** [comment]
PR is in :) Sorry for the waiting time
