### ISSUE TITLE
All /lib/js/* files are missing from master branch

### ISSUE THREAD

**Issue by alkisg** [literallycanvas/literallycanvas#497]
> $ cat lib/js/.gitignore 
> *
> !.gitignore
> !.npmignore

Is that * there on purpose? I tried to clone the master branch and open the demo, but all the lib/js/* files are ignored by git and they're missing, so the demo isn't working... or did I do something wrong?

**Comment by irskep** [comment]
You have to run `gulp` to build the JS.
