### ISSUE TITLE
Error while importing literallycanvas in create-react-app

### ISSUE THREAD

**Issue by TRomesh** [literallycanvas/literallycanvas#505]
Im getting the following error in browser console while importing .... in create-react-app, **Uncaught Can't find createReactClass** . looks like there is still some dependency issues. Any workaround to this?
Here is the code i have tried to load the canvas component.
```
import React, { Component } from "react";
import { LiterallyCanvasReactComponent as LC } from "literallycanvas";
import LiterallyCanvas from "literallycanvas/lib/js/core/LiterallyCanvas";
import defaultOptions from "literallycanvas/lib/js/core/defaultOptions";

class App extends Component {
  constructor(props) {
    super(props);
    defaultOptions.imageSize.width = 600;
    defaultOptions.imageSize.height = 400;
    this.lc = new LiterallyCanvas(defaultOptions);
  }
  render() {
    return <LC lc={this.lc} />;
  }
}

export default App;

```

**Comment by irskep** [comment]
Maybe @jarlep can help you. They submitted the most recent fix for JS imports.

**Comment by irskep** [comment]
Oh - you need to add `create-react-class` as a dependency, since they removed it from React itself.

**Comment by TRomesh** [comment]
Thanks @jarlep i also had to add `react-dom-factories` dependency to get it working.
