### ISSUE TITLE
Don't save shapes with 0px size

### ISSUE THREAD

**Issue by ggomez91** [literallycanvas/literallycanvas#507]
When you use the Ellipse, Rectangle or Line tools and click on the canvas without dragging a 0px-size shape is saved to the snapshot. This shape is not rendered but it augments the number of shapes which could be a problem for some implementations. This 0px shapes cannot be selected with the Select Tool nor deleted. 

A possible fix is in [this PR](https://github.com/literallycanvas/literallycanvas/pull/506)

**Comment by irskep** [comment]
Your PR made my day! 🎉
