### ISSUE TITLE
Localisation for undo, redo, zoomin and zoom out doesnt work

### ISSUE THREAD

**Issue by rohitharkhani** [literallycanvas/literallycanvas#508]
Localisation for undo, redo, zoomin and zoom out doesnt work

**Comment by rohitharkhani** [comment]
I have fixed it and created pull request for it. #509

**Comment by irskep** [comment]
I wish I could press a button and mail people trophies when they open a ticket and immediately fix it. :-D

**Comment by rohitharkhani** [comment]
How about new NPM version. Do i need to do anything special or automatic build will be triggered?
Also when i was setting up project there is gap in read me, npm install doesn't work because dependency tree generated using yarn so yarn required. I will create package-lock.json and create separate pull request.

**Comment by rohitharkhani** [comment]
#510 I have created pull request to fix error created by last pull request.
