### ISSUE TITLE
How to use literallycanvas`API with React

### ISSUE THREAD

**Issue by sjcUD** [literallycanvas/literallycanvas#512]
hello  guys,thanks for your cool project , i am using react to build my web ,and  i want to use literallycanvas with react ,I find out the [API website](http://literallycanvas.com/api/index.html) ,but i do not know  how to use the API with react ,i can`t find out any example ,Is there anyone who knows how to use the API , or is there any examples that use react ?

my code show as following:

`import React, { Component } from "react";
import LC from "literallycanvas";
class CanvasTest extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
        }
    }
    render() {
        return(
            <div>
              
                <LC.LiterallyCanvasReactComponent
                    onInit={(lc) => {
                        console.log("initialized with", lc)
                    }}
                    imageURLPrefix='node_modules/literallycanvas/lib/img/' />
            </div>
        )
    }
}

export default CanvasTest;`

**Comment by irskep** [comment]
Github Issues is not a help forum. Please use the mailing list linked in the sidebar of the web site.
