### ISSUE TITLE
Generating bitmap server-side (dotnet)

### ISSUE THREAD

**Issue by mikolus** [literallycanvas/literallycanvas#513]
Hi,
Has anyone tried generating png image from LiterallyCanvas' snapshot in dotnet?
My client is generating a lot of documents containing a lot of drawings. I create PDFs of them on the server and have to store both bitmaps and JSON snapshots because I can generate the bitmap only in javascript. I didn't realize how quickly it will fill up the server and have to figure out a way to avoid storing the bitmaps in the database.

Any suggestions will be appreciated.

**Comment by irskep** [comment]
Github Issues is not a help forum; please use the mailing list linked in the sidebar of the web site.
