### ISSUE TITLE
which way is good 

### ISSUE THREAD

**Issue by masudchowdhuryca** [literallycanvas/literallycanvas#535]
hi all
I have found to use literal canvas in different style such as  The classic style has two way one is with GUI and without GUI. Besides there is another option to use core . My question which option i should adopt and which one is better and advantage and disadvantage of each way
regards
masud 

Classic Style

Here’s a basic working setup. Each part is required.

<html>
  <head>
    
    <link href="/static/css/literallycanvas.css" rel="stylesheet">

    
    <script src="//cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-with-addons.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js"></script>

    
    <script src="/static/js/literallycanvas.js"></script>
  </head>
  <body>
    
    
    <div class="my-drawing"></div>

    
    <script>
        LC.init(
            document.getElementsByClassName('my-drawing')[0],
            {imageURLPrefix: '/static/img'}
        );
    </script>
  </body>
</html>

React.js Style

Literally Canvas can be used as a React component!

<html>
  <head>
    
    <link href="/static/css/literallycanvas.css" rel="stylesheet">

    
    <script src="//cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-with-addons.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>

    
    <script src="/static/js/literallycanvas.js"></script>
  </head>
  <body>
    <div id="root"></div>

    <script type="text/babel">
        ReactDOM.render(
            <div>
                <LC.LiterallyCanvasReactComponent imageURLPrefix="/static/img" />
            </div>,
            document.getElementById('root'));
    </script>
  </body>
</html>

**Comment by irskep** [comment]
Do you use React? Use the React component. Do you not? Then don't.

Do you want to write your own UI? Use the core build. Do you want the built-in GUI? Then use the regular build.
