### ISSUE TITLE
How can I import a fork of this repository on my node project?

### ISSUE THREAD

**Issue by papeixoto** [literallycanvas/literallycanvas#544]
Hello.
I need to change some functionalities of literally canvas on my project but I'm unable to import it from my github.
I've tried to just change the source in package.json to my repository, doing a post install script, copying directly literallycanvas.js to my src folder but nothing seems to work. 
If I go the package route I always get: Module not found: Can't resolve 'literallycanvas' in '...'

**Comment by irskep** [comment]
This doesn't sound like something I'll be able to help with.
