### ISSUE TITLE
Why can't your document add a complete demo to create your own shape???

### ISSUE THREAD

**Issue by dingguoqing513** [literallycanvas/literallycanvas#549]

**Comment by dingguoqing513** [comment]
I'm puzzled. Is the document only for basic users???

**Comment by irskep** [comment]
<img width="895" alt="Screen Shot 2020-04-26 at 9 50 37 AM" src="https://user-images.githubusercontent.com/40085/80313992-6577f200-87a3-11ea-8c66-62155526fc7d.png">
