### ISSUE TITLE
Zoom to 0.2 and Pan issues

### ISSUE THREAD

**Issue by AdrianLove** [literallycanvas/literallycanvas#57]
Hey everyone, 

I haven't used much coffeescript before but I'm interested in trying to wrap my head around what you guys have provided already. I seem to have the coffeescript watching and compiling correctly which I'm pretty excited about. 

I found a bug where if you zoom to 0.2 or 0.4 and try to pan (in Chrome and FF latest) the canvas freaks out and is lost forever. Just reporting it at this point.

Thanks.

**Comment by irskep** [comment]
Fixed for v0.4.5.
