### ISSUE TITLE
Convert everything to use pointer events

### ISSUE THREAD

**Issue by campaul** [literallycanvas/literallycanvas#72]
Pointer events are awesome and would provide us a unified method of handling input across devices (mouse, touch, pen). Since IE and Firefox the only thing that support them at the moment, a normalization layer would be needed, but this is really simple to implement.

Before anyone panics about implementing something Microsoft made up, it has a real [W3C Recommendation](http://www.w3.org/TR/pointerevents/).

**Comment by irskep** [comment]
I'd rather not do this. Touch and mouse events are a more reliable standard from what I can tell of the browser climate.

**Comment by irskep** [comment]
I take it all back. We should do this.

**Comment by irskep** [comment]
Just kidding. I'm not a big fan of using shims for stuff like this (one more source of bugs) and our existing setup has been fine.
